/** @file Playwright component testing configuration. */
import vitePluginYaml from '@modyfi/vite-plugin-yaml'
import * as componentTesting from '@playwright/experimental-ct-react'

// This is an autogenerated file.
/* eslint-disable @typescript-eslint/strict-boolean-expressions, @typescript-eslint/no-magic-numbers */
export default componentTesting.defineConfig({
  testDir: './test-component',
  snapshotDir: './__snapshots__',
  timeout: 10_000,
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  ...(process.env.CI ? { workers: 1 } : {}),
  projects: [
    {
      name: 'chromium',
      use: { ...componentTesting.devices['Desktop Chrome'] },
    },
    {
      name: 'firefox',
      use: { ...componentTesting.devices['Desktop Firefox'] },
    },
    ...(process.env.CI
      ? []
      : [
          {
            name: 'webkit',
            use: { ...componentTesting.devices['Desktop Safari'] },
          },
        ]),
  ],
  use: {
    trace: 'on-first-retry',
    ctPort: 3100,
    ctViteConfig: {
      plugins: [vitePluginYaml()],
      define: {
        // These are constants, and MUST be `CONSTANT_CASE`.
        // eslint-disable-next-line @typescript-eslint/naming-convention
        ['REDIRECT_OVERRIDE']: 'undefined',
        // eslint-disable-next-line @typescript-eslint/naming-convention
        ['process.env.NODE_ENV']: JSON.stringify('production'),
      },
    },
  },
})
