## Language Server's application.conf

akka {
  actor.debug.lifecycle = off
  http {
      server {
          idle-timeout = infinite
          remote-address-header = on
          websocket.periodic-keep-alive-max-idle = 1 second
      }
  }
  https {
      pkcs12-file = ${?ENSO_HTTPS_PKCS12_PATH}
      pkcs12-password = ${?ENSO_HTTPS_PKCS12_PASSWORD}
      public-certificate = ${?ENSO_HTTPS_PUBLIC_CERTIFICATE}
      public-certificate-algorithm = "X.509"
      public-certificate-algorithm = ${?ENSO_HTTPS_PUBLIC_CERTIFICATE_ALGORITHM}
      private-key = ${?ENSO_HTTPS_PRIVATE_KEY}
      ssl-type = "TLS"
      ssl-type = ${?ENSO_HTTPS_SSL}
      trust-self-signed = true
      trust-self-sgined = ${?ENSO_HTTPS_TRUST_SELF_SIGNED}
  }
  log-dead-letters = 1
  log-dead-letters-during-shutdown = off
  jvm-shutdown-hooks = off
  library-extensions = ["akka.stream.SystemMaterializer$"]
  use-slf4j = on
  log-level = "warning"
  stdout-loglevel = "warning"
}

logging-service {
  logger {
    akka.actor = warn
    akka.event = error
    akka.routing = error
    akka.io = error
    akka.stream = error
    io.helidon = warn
    java.lang.ProcessBuilder = warn
    org.eclipse.jgit = error
    # Log levels to limit during very verbose setting
    org.enso.interpreter.epb.HostClassLoader = error
    org.enso.jsonrpc.JsonRpcServer = debug
    org.enso.languageserver.protocol.json.JsonConnectionController = debug
    org.enso.languageserver.runtime.RuntimeConnector = debug
    org.enso.ydoc.polyfill.web = warn
    org.enso.ydoc.polyfill.ParserPolyfill = warn
    org.enso.persist = warn
    Standard.Base.Logging.Progress = error
  }
  appenders = [
    {
        name = "socket"
        hostname = "localhost"
        hostname = ${?ENSO_LOGSERVER_HOSTNAME}
        port = 6000
        port = ${?ENSO_LOGSERVER_PORT}
    },
    {
        name = "console"
    }
  ]
  default-appender = socket
  default-appender = ${?ENSO_APPENDER_DEFAULT}
  server {
    start = true
    start = ${?ENSO_LOGSERVER_START}
    port = 6000
    port = ${?ENSO_LOGSERVER_PORT}
    log-to-file {
      enable = true
      enable = ${?ENSO_LOGSERVER_LOG_TO_FILE}
      log-level = debug
      log-level = ${?ENSO_LOGSERVER_LOG_TO_FILE_LOG_LEVEL}
    }
    appenders = [ # file/console/socket/telemetry/opensearch
        {
          name = "file"
          rolling-policy {
            max-file-size = "100MB"
            max-history = 30
            max-total-size = "2GB"
          },
          immediate-flush = true
        },
        {
          name = "opensearch",
          uri = "https://api.cloud.enso.org"
          uri = ${?ENSO_CLOUD_API_URL}
          log-connection-failures = false
          log-connection-failures = ${?ENSO_LOGSERVER_LOG_ERRORS}
          log-level = debug
          log-level = ${?ENSO_LOGSERVER_REMOTE_LOG_LEVEL}
          enabled = true
          enabled = ${?ENSO_OPENSEARCH_APPENDER_ENABLED}
        },
        {
          name = "telemetry"
          uri = "https://api.cloud.enso.org"
          uri = ${?ENSO_CLOUD_API_URL}
          log-connection-failures = false
          log-connection-failures = ${?ENSO_LOGSERVER_LOG_ERRORS}
        },
        {
          name = "console"
        }
    ]
    default-appender = console
    default-appender = ${?ENSO_LOGSERVER_APPENDER}
  }
}

language-server {
  ydoc {
    hostname = "localhost"
    hostname = ${?LANGUAGE_SERVER_YDOC_HOSTNAME}
    port = 5976
    port = ${?LANGUAGE_SERVER_YDOC_PORT}
  }
}
