#![allow(clippy::all)]
#![allow(unknown_lints)]
#![allow(missing_copy_implementations)]
#![allow(missing_debug_implementations)]
#![allow(missing_docs)]
#![allow(trivial_casts)]
#![allow(trivial_numeric_casts)]
#![allow(unsafe_code)]
#![allow(unused_import_braces)]

//! This file includes all contents generated by lexer specialization.


include!("lexer-engine.rs");
