name:       luna-shell
version:    "1.2"
author:     Luna Team <contact@luna-lang.org>
maintainer: Luna Team <contact@luna-lang.org>

library:
    source-dirs:
        - src
    dependencies:
        - base
        - bimap
        - containers
        - directory
        - filepath
        - layered-state
        - lens
        - luna-core
        - luna-exception
        - luna-package
        - luna-passes
        - luna-runtime
        - luna-stdlib
        - luna-syntax-text-parser
        - megaparsec
        - mtl
        - optparse-applicative
        - path
        - prologue
        - text
        - unordered-containers
        - yaml

executables:
    luna:
        main: src-app/Main.hs
        ghc-options: -threaded "-with-rtsopts=-N -T"
        dependencies:
            - base
            - luna-shell
            - prologue

benchmarks:
    interpreter-benchmark:
        main: Main.hs
        source-dirs:
            - test/bench
        ghc-options:
            - -rtsopts
            - -threaded
            - -with-rtsopts=-N
            - -with-rtsopts=-T
        dependencies:
            - base
            - directory
            - filepath
            - luna-benchmark
            - luna-exception
            - luna-package
            - luna-shell
            - path
            - prologue
            - template-haskell


default-extensions:
    - AllowAmbiguousTypes
    - ApplicativeDo
    - Arrows
    - BangPatterns
    - BinaryLiterals
    - ConstraintKinds
    - DataKinds
    - DefaultSignatures
    - DeriveDataTypeable
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    - DeriveTraversable
    - DoAndIfThenElse
    - DuplicateRecordFields
    - EmptyDataDecls
    - FlexibleContexts
    - FlexibleInstances
    - FunctionalDependencies
    - GeneralizedNewtypeDeriving
    - InstanceSigs
    - LambdaCase
    - LiberalTypeSynonyms
    - MonadComprehensions
    - MultiWayIf
    - NamedWildCards
    - NegativeLiterals
    - NoImplicitPrelude
    - NumDecimals
    - OverloadedLabels
    - OverloadedStrings
    - PackageImports
    - QuasiQuotes
    - RankNTypes
    - RecursiveDo
    - RelaxedPolyRec
    - ScopedTypeVariables
    - StandaloneDeriving
    - TemplateHaskell
    - TupleSections
    - TypeApplications
    - TypeFamilies
    - TypeFamilyDependencies
    - TypeOperators
    - ViewPatterns

