/** @file Kinds of lambda. */
import type { SvgUseIcon } from '#/components/types'
import { includesPredicate } from '$/utils/data/array'
import type { TextId } from 'enso-common/src/text'

/** Possible kinds of audit log entry, excluding the "get secret" endpoint. */
export type LambdaKind = (typeof LAMBDA_KINDS)[number]

/** Attempt to validate an arbitrary string into a {@link LambdaKind}. */
export function normalizeLambdaKind(lambdaKind: string) {
  if (/^GET .+\{SECRET_ID\}$/.test(lambdaKind)) {
    return { valid: true, kind: 'GET /secrets/{SECRET_ID}' } as const
  }
  if (isLambdaKind(lambdaKind)) {
    return { valid: true, kind: lambdaKind } as const
  }
  return { valid: false, invalidKind: lambdaKind } as const
}

export const DEFAULT_EVENT_ICON = 'log' satisfies SvgUseIcon

/** Lambda kinds for events, ordered roughly in order of decreasing level of admin access. */
export const LAMBDA_KINDS = [
  'POST /auth',
  'GET /organizations/me',
  'PATCH /organizations/me',
  'PUT /organizations/me/picture',
  'POST /logs',
  'GET /invitations',
  'DELETE /invitations',
  'POST /payments/subscriptions',
  'GET /payments/subscriptions/{SUBSCRIPTION_ID}',
  'DELETE /payments/subscriptions/{SUBSCRIPTION_ID}',
  'GET /usergroups',
  'POST /usergroups',
  'DELETE /usergroups/{USER_GROUP_ID}',
  'GET /users',
  'POST /users',
  'POST /users/invite',
  'GET /users/me',
  'PUT /users/me',
  'DELETE /users/me',
  'PUT /users/me/picture',
  'PUT /users/{USER_ID}/usergroups',
  'GET /tags',
  'POST /tags',
  'DELETE /tags/{TAG_ID}',
  'GET /log_events',
  'PATCH /assets',
  'DELETE /assets/{ASSET_ID}',
  'POST /assets/{ASSET_ID}/copy',
  'PATCH /assets/{ASSET_ID}',
  'PATCH /assets/{ASSET_ID}/labels',
  'PATCH /assets/{ASSET_ID}/touch',
  'GET /assets/{ASSET_ID}/versions',
  'POST /assets/{ASSET_ID}/versions/restore',
  'POST /permissions',
  'POST /projects',
  'GET /projects/{PROJECT_ID}',
  'PUT /projects/{PROJECT_ID}',
  'GET /projects/{PROJECT_ID}/contents',
  'GET /projects/{PROJECT_ID}/files',
  'POST /projects/{PROJECT_ID}/open',
  'POST /projects/{PROJECT_ID}/close',
  'POST /projects/{PROJECT_ID}/upload',
  'POST /projects/{PROJECT_ID}/versions/restore',
  'POST /projects/{PROJECT_ID}/versions/clone',
  'POST /projects/{PROJECT_ID}/hybrid_set_opened',
  'POST /projects/{PROJECT_ID}/hybrid_set_open_in_progress',
  'GET /projects/{PROJECT_ID}/executions',
  'POST /projects/{PROJECT_ID}/executions/new',
  'GET /project-sessions',
  'GET /project-sessions/{PROJECT_SESSION_ID}/logs',
  'GET /executions/{EXECUTION_ID}',
  'DELETE /executions/{EXECUTION_ID}',
  'POST /files',
  'GET /files',
  'GET /files/{FILE_ID}',
  'GET /files/{FILE_ID}/contents',
  'POST /files/upload/start',
  'POST /files/upload/end',
  'POST /datalinks',
  'GET /datalinks/{DATALINK_ID}',
  'DELETE /datalinks/{DATALINK_ID}',
  'POST /directories',
  'GET /directories/{DIRECTORY_ID}',
  'PUT /directories/{DIRECTORY_ID}',
  'DELETE /directories/{DIRECTORY_ID}',
  'POST /secrets',
  'GET /secrets',
  'GET /secrets/{SECRET_ID}',
  'PUT /secrets/{SECRET_ID}',
  'DELETE /secrets/{SECRET_ID}',
  'POST /configurations',
  'GET /configurations',
  'GET /configurations/{CONFIGURATION_ID}',
  'GET /path/resolve',
] as const

// eslint-disable-next-line no-restricted-syntax
export const isLambdaKind = includesPredicate(LAMBDA_KINDS)

/* eslint-disable @typescript-eslint/naming-convention */
export const IS_EVENT_HIDDEN_BY_DEFAULT: Partial<Record<LambdaKind, true>> = {
  'GET /directories/{DIRECTORY_ID}': true,
  'GET /organizations/me': true,
  'GET /usergroups': true,
  'GET /users': true,
  'GET /tags': true,
  'GET /log_events': true,
  'GET /projects/{PROJECT_ID}/executions': true,
  'GET /projects/{PROJECT_ID}': true,
  'POST /projects/{PROJECT_ID}/hybrid_set_open_in_progress': true,
  'POST /files/upload/start': true,
}

export const SELECTABLE_LAMBDA_KINDS = LAMBDA_KINDS.filter(
  (kind) => IS_EVENT_HIDDEN_BY_DEFAULT[kind] !== true,
)

export const EVENT_TYPE_ICON: Record<LambdaKind, SvgUseIcon> = {
  'POST /auth': 'icon/lock',
  'GET /organizations/me': 'home2',
  'PATCH /organizations/me': 'home2',
  'PUT /organizations/me/picture': 'image',
  'POST /logs': 'log',
  'GET /invitations': 'email',
  'DELETE /invitations': 'trash',
  'POST /payments/subscriptions': 'redo',
  'GET /payments/subscriptions/{SUBSCRIPTION_ID}': 'redo',
  'DELETE /payments/subscriptions/{SUBSCRIPTION_ID}': 'trash',
  'GET /usergroups': 'people',
  'POST /usergroups': 'people',
  'DELETE /usergroups/{USER_GROUP_ID}': 'trash',
  'GET /users': 'people',
  'POST /users': 'people',
  'POST /users/invite': 'email',
  'GET /users/me': 'default_user',
  'PUT /users/me': 'default_user',
  'DELETE /users/me': 'trash',
  'PUT /users/me/picture': 'image',
  'PUT /users/{USER_ID}/usergroups': 'people',
  'GET /tags': 'tag',
  'POST /tags': 'tag',
  'DELETE /tags/{TAG_ID}': 'tag',
  'GET /log_events': 'log',
  'PATCH /assets': 'document',
  'DELETE /assets/{ASSET_ID}': 'trash',
  'POST /assets/{ASSET_ID}/copy': 'document',
  'PATCH /assets/{ASSET_ID}': 'document',
  'PATCH /assets/{ASSET_ID}/labels': 'tag',
  'PATCH /assets/{ASSET_ID}/touch': 'document',
  'GET /assets/{ASSET_ID}/versions': 'undo',
  'POST /assets/{ASSET_ID}/versions/restore': 'redo',
  'POST /permissions': 'icon/lock',
  'POST /projects': 'graph_add',
  'GET /projects/{PROJECT_ID}': 'graph',
  'PUT /projects/{PROJECT_ID}': 'graph',
  'GET /projects/{PROJECT_ID}/contents': 'log',
  'GET /projects/{PROJECT_ID}/files': 'document',
  'POST /projects/{PROJECT_ID}/open': 'workflow_play',
  'POST /projects/{PROJECT_ID}/close': 'close',
  'POST /projects/{PROJECT_ID}/upload': 'data_upload',
  'POST /projects/{PROJECT_ID}/versions/restore': 'redo',
  'POST /projects/{PROJECT_ID}/versions/clone': 'clone',
  'POST /projects/{PROJECT_ID}/hybrid_set_opened': 'open',
  'POST /projects/{PROJECT_ID}/hybrid_set_open_in_progress': 'open',
  'GET /projects/{PROJECT_ID}/executions': 'schedule',
  'POST /projects/{PROJECT_ID}/executions/new': 'schedule',
  'GET /project-sessions': 'log',
  'GET /project-sessions/{PROJECT_SESSION_ID}/logs': 'log',
  'GET /executions/{EXECUTION_ID}': 'schedule',
  'DELETE /executions/{EXECUTION_ID}': 'trash',
  'POST /files': 'document',
  'GET /files': 'document',
  'GET /files/{FILE_ID}': 'document',
  'GET /files/{FILE_ID}/contents': 'log',
  'POST /files/upload/start': 'data_upload',
  'POST /files/upload/end': 'data_upload',
  'POST /datalinks': 'connector_add',
  'GET /datalinks/{DATALINK_ID}': 'connector',
  'DELETE /datalinks/{DATALINK_ID}': 'trash',
  'POST /directories': 'folder_add',
  'GET /directories/{DIRECTORY_ID}': 'folder',
  'PUT /directories/{DIRECTORY_ID}': 'folder',
  'DELETE /directories/{DIRECTORY_ID}': 'trash',
  'POST /secrets': 'key_add',
  'GET /secrets': 'key',
  'GET /secrets/{SECRET_ID}': 'key',
  'PUT /secrets/{SECRET_ID}': 'key',
  'DELETE /secrets/{SECRET_ID}': 'trash',
  'POST /configurations': 'connector_add',
  'GET /configurations': 'connector',
  'GET /configurations/{CONFIGURATION_ID}': 'connector',
  'GET /path/resolve': 'path2',
}

export const EVENT_TYPE_NAME_ID: Record<LambdaKind, TextId & `${string}LogEvent`> = {
  'POST /auth': 'authLogEvent',
  'GET /organizations/me': 'getOrganizationLogEvent',
  'PATCH /organizations/me': 'updateOrganizationLogEvent',
  'PUT /organizations/me/picture': 'uploadOrganizationPictureLogEvent',
  'POST /logs': 'postLogEventLogEvent',
  'GET /invitations': 'listInvitationsLogEvent',
  'DELETE /invitations': 'deleteInvitationLogEvent',
  'POST /payments/subscriptions': 'createSubscriptionLogEvent',
  'GET /payments/subscriptions/{SUBSCRIPTION_ID}': 'getSubscriptionLogEvent',
  'DELETE /payments/subscriptions/{SUBSCRIPTION_ID}': 'deleteSubscriptionLogEvent',
  'GET /usergroups': 'listUserGroupsLogEvent',
  'POST /usergroups': 'createUserGroupLogEvent',
  'DELETE /usergroups/{USER_GROUP_ID}': 'deleteUserGroupLogEvent',
  'GET /users': 'listUsersLogEvent',
  'POST /users': 'createUserLogEvent',
  'POST /users/invite': 'inviteUserLogEvent',
  'GET /users/me': 'getSelfUserLogEvent',
  'PUT /users/me': 'updateSelfUserLogEvent',
  'DELETE /users/me': 'deleteSelfUserLogEvent',
  'PUT /users/me/picture': 'uploadSelfUserPictureLogEvent',
  'PUT /users/{USER_ID}/usergroups': 'updateUserUserGroupsLogEvent',
  'GET /tags': 'listLabelsLogEvent',
  'POST /tags': 'createLabelLogEvent',
  'DELETE /tags/{TAG_ID}': 'deleteLabelLogEvent',
  'GET /log_events': 'listLogEventsLogEvent',
  'PATCH /assets': 'undoDeleteAssetLogEvent',
  'DELETE /assets/{ASSET_ID}': 'deleteAssetLogEvent',
  'POST /assets/{ASSET_ID}/copy': 'copyAssetLogEvent',
  'PATCH /assets/{ASSET_ID}': 'updateAssetLogEvent',
  'PATCH /assets/{ASSET_ID}/labels': 'updateAssetLabelsLogEvent',
  'PATCH /assets/{ASSET_ID}/touch': 'touchAssetLogEvent',
  'GET /assets/{ASSET_ID}/versions': 'listAssetVersionsLogEvent',
  'POST /assets/{ASSET_ID}/versions/restore': 'rewindAssetLogEvent',
  'POST /permissions': 'createPermissionLogEvent',
  'POST /projects': 'createProjectLogEvent',
  'GET /projects/{PROJECT_ID}': 'getProjectDetailsLogEvent',
  'PUT /projects/{PROJECT_ID}': 'updateProjectLogEvent',
  'GET /projects/{PROJECT_ID}/contents': 'getProjectContentsLogEvent',
  'GET /projects/{PROJECT_ID}/files': 'getProjectFilesLogEvent',
  'POST /projects/{PROJECT_ID}/open': 'openProjectLogEvent',
  'POST /projects/{PROJECT_ID}/close': 'closeProjectLogEvent',
  'POST /projects/{PROJECT_ID}/upload': 'updateProjectFilesLogEvent',
  'POST /projects/{PROJECT_ID}/versions/restore': 'rewindProjectLogEvent',
  'POST /projects/{PROJECT_ID}/versions/clone': 'cloneProjectLogEvent',
  'POST /projects/{PROJECT_ID}/hybrid_set_opened': 'setHybridOpenedLogEvent',
  'POST /projects/{PROJECT_ID}/hybrid_set_open_in_progress': 'setHybridOpenInProgressLogEvent',
  'GET /projects/{PROJECT_ID}/executions': 'listProjectExecutionsLogEvent',
  'POST /projects/{PROJECT_ID}/executions/new': 'createProjectExecutionLogEvent',
  'GET /project-sessions': 'listProjectSessionsLogEvent',
  'GET /project-sessions/{PROJECT_SESSION_ID}/logs': 'getProjectSessionLogsLogEvent',
  'GET /executions/{EXECUTION_ID}': 'getExecutionLogEvent',
  'DELETE /executions/{EXECUTION_ID}': 'deleteExecutionLogEvent',
  'POST /files': 'createFileLogEvent',
  'GET /files': 'listFilesLogEvent',
  'GET /files/{FILE_ID}': 'getFileDetailsLogEvent',
  'GET /files/{FILE_ID}/contents': 'getFileContentsLogEvent',
  'POST /files/upload/start': 'uploadFileStartLogEvent',
  'POST /files/upload/end': 'uploadFileEndLogEvent',
  'POST /datalinks': 'createDatalinkLogEvent',
  'GET /datalinks/{DATALINK_ID}': 'getDatalinkLogEvent',
  'DELETE /datalinks/{DATALINK_ID}': 'deleteDatalinkLogEvent',
  'POST /directories': 'createDirectoryLogEvent',
  'GET /directories/{DIRECTORY_ID}': 'getDirectoryLogEvent',
  'PUT /directories/{DIRECTORY_ID}': 'updateDirectoryLogEvent',
  'DELETE /directories/{DIRECTORY_ID}': 'deleteDirectoryLogEvent',
  'POST /secrets': 'createSecretLogEvent',
  'GET /secrets': 'listSecretsLogEvent',
  'GET /secrets/{SECRET_ID}': 'getSecretLogEvent',
  'PUT /secrets/{SECRET_ID}': 'updateSecretLogEvent',
  'DELETE /secrets/{SECRET_ID}': 'deleteSecretLogEvent',
  'POST /configurations': 'createConfigurationLogEvent',
  'GET /configurations': 'listConfigurationsLogEvent',
  'GET /configurations/{CONFIGURATION_ID}': 'getConfigurationLogEvent',
  'GET /path/resolve': 'resolvePathLogEvent',
}
/* eslint-enable @typescript-eslint/naming-convention */
