/** @file Kinds of lambda. */
import DataUploadIcon from '#/assets/data_upload.svg'
import KeyIcon from '#/assets/key.svg'
import Play2Icon from '#/assets/play2.svg'
import TrashIcon from '#/assets/trash.svg'
import type { IconPropSvgUse, SvgUseIcon } from '#/components/AriaComponents'
import { includesPredicate } from '#/utilities/array'
import type { TextId } from 'enso-common/src/text'

/** Possible kinds of audit log entry, excluding the "get secret" endpoint. */
export type LambdaKind = (typeof ORDERED_LAMBDA_KINDS)[number]

/** Attempt to validate an arbitrary string into a {@link LambdaKind}. */
export function normalizeLambdaKind(lambdaKind: string) {
  if (/^GET .+\{SECRET_ID\}$/.test(lambdaKind)) {
    return { valid: true, kind: 'GET /secrets/{SECRET_ID}' } as const
  }
  if (isLambdaKind(lambdaKind)) {
    return { valid: true, kind: lambdaKind } as const
  }
  return { valid: false, invalidKind: lambdaKind } as const
}

export const DEFAULT_EVENT_ICON = 'log' satisfies SvgUseIcon

/** Lambda kinds for events, ordered roughly in order of decreasing level of admin access. */
export const ORDERED_LAMBDA_KINDS = [
  'POST /auth',
  'GET /organizations/me',
  'PATCH /organizations/me',
  'PUT /organizations/me/picture',
  'POST /logs',
  'GET /invitations',
  'DELETE /invitations',
  'POST /payments/subscriptions',
  'GET /payments/subscriptions/{SUBSCRIPTION_ID}',
  'DELETE /payments/subscriptions/{SUBSCRIPTION_ID}',
  'GET /usergroups',
  'POST /usergroups',
  'DELETE /usergroups/{USER_GROUP_ID}',
  'GET /users',
  'POST /users',
  'POST /users/invite',
  'GET /users/me',
  'PUT /users/me',
  'DELETE /users/me',
  'PUT /users/me/picture',
  'PUT /users/{USER_ID}/usergroups',
  'GET /tags',
  'POST /tags',
  'DELETE /tags/{TAG_ID}',
  'GET /log_events',
  'PATCH /assets',
  'DELETE /assets/{ASSET_ID}',
  'POST /assets/{ASSET_ID}/copy',
  'PATCH /assets/{ASSET_ID}',
  'PATCH /assets/{ASSET_ID}/labels',
  'PATCH /assets/{ASSET_ID}/touch',
  'GET /assets/{ASSET_ID}/versions',
  'POST /assets/{ASSET_ID}/versions/restore',
  'POST /permissions',
  'POST /projects',
  'GET /projects/{PROJECT_ID}',
  'PUT /projects/{PROJECT_ID}',
  'GET /projects/{PROJECT_ID}/contents',
  'GET /projects/{PROJECT_ID}/files',
  'POST /projects/{PROJECT_ID}/open',
  'POST /projects/{PROJECT_ID}/close',
  'POST /projects/{PROJECT_ID}/upload',
  'POST /projects/{PROJECT_ID}/versions/restore',
  'POST /projects/{PROJECT_ID}/versions/clone',
  'POST /projects/{PROJECT_ID}/hybrid_set_opened',
  'POST /projects/{PROJECT_ID}/hybrid_set_open_in_progress',
  'GET /projects/{PROJECT_ID}/executions',
  'POST /projects/{PROJECT_ID}/executions/new',
  'GET /project-sessions',
  'GET /project-sessions/{PROJECT_SESSION_ID}/logs',
  'GET /executions/{EXECUTION_ID}',
  'DELETE /executions/{EXECUTION_ID}',
  'POST /files',
  'GET /files',
  'GET /files/{FILE_ID}',
  'GET /files/{FILE_ID}/contents',
  'POST /files/upload/start',
  'POST /files/upload/end',
  'POST /datalinks',
  'GET /datalinks/{DATALINK_ID}',
  'DELETE /datalinks/{DATALINK_ID}',
  'POST /directories',
  'GET /directories/{DIRECTORY_ID}',
  'PUT /directories/{DIRECTORY_ID}',
  'DELETE /directories/{DIRECTORY_ID}',
  'POST /secrets',
  'GET /secrets',
  'GET /secrets/{SECRET_ID}',
  'PUT /secrets/{SECRET_ID}',
  'DELETE /secrets/{SECRET_ID}',
  'POST /configurations',
  'GET /configurations',
  'GET /configurations/{CONFIGURATION_ID}',
  'GET /path/resolve',
] as const

// eslint-disable-next-line no-restricted-syntax
export const isLambdaKind = includesPredicate(ORDERED_LAMBDA_KINDS)

/* eslint-disable @typescript-eslint/naming-convention */
export const EVENT_TYPE_ICON: Record<LambdaKind, IconPropSvgUse<never> | (string & {})> = {
  'POST /auth': '',
  'GET /organizations/me': '',
  'PATCH /organizations/me': '',
  'PUT /organizations/me/picture': '',
  'POST /logs': '',
  'GET /invitations': '',
  'DELETE /invitations': '',
  'POST /payments/subscriptions': '',
  'GET /payments/subscriptions/{SUBSCRIPTION_ID}': '',
  'DELETE /payments/subscriptions/{SUBSCRIPTION_ID}': '',
  'GET /usergroups': '',
  'POST /usergroups': '',
  'DELETE /usergroups/{USER_GROUP_ID}': '',
  'GET /users': '',
  'POST /users': '',
  'POST /users/invite': '',
  'GET /users/me': '',
  'PUT /users/me': '',
  'DELETE /users/me': '',
  'PUT /users/me/picture': '',
  'PUT /users/{USER_ID}/usergroups': '',
  'GET /tags': '',
  'POST /tags': '',
  'DELETE /tags/{TAG_ID}': '',
  'GET /log_events': '',
  'PATCH /assets': '',
  'DELETE /assets/{ASSET_ID}': TrashIcon,
  'POST /assets/{ASSET_ID}/copy': '',
  'PATCH /assets/{ASSET_ID}': '',
  'PATCH /assets/{ASSET_ID}/labels': '',
  'PATCH /assets/{ASSET_ID}/touch': '',
  'GET /assets/{ASSET_ID}/versions': '',
  'POST /assets/{ASSET_ID}/versions/restore': '',
  'POST /permissions': '',
  'POST /projects': '',
  'GET /projects/{PROJECT_ID}': '',
  'PUT /projects/{PROJECT_ID}': '',
  'GET /projects/{PROJECT_ID}/contents': '',
  'GET /projects/{PROJECT_ID}/files': '',
  'POST /projects/{PROJECT_ID}/open': Play2Icon,
  'POST /projects/{PROJECT_ID}/close': '',
  'POST /projects/{PROJECT_ID}/upload': '',
  'POST /projects/{PROJECT_ID}/versions/restore': '',
  'POST /projects/{PROJECT_ID}/versions/clone': '',
  'POST /projects/{PROJECT_ID}/hybrid_set_opened': '',
  'POST /projects/{PROJECT_ID}/hybrid_set_open_in_progress': '',
  'GET /projects/{PROJECT_ID}/executions': '',
  'POST /projects/{PROJECT_ID}/executions/new': '',
  'GET /project-sessions': '',
  'GET /project-sessions/{PROJECT_SESSION_ID}/logs': '',
  'GET /executions/{EXECUTION_ID}': '',
  'DELETE /executions/{EXECUTION_ID}': '',
  'POST /files': '',
  'GET /files': '',
  'GET /files/{FILE_ID}': '',
  'GET /files/{FILE_ID}/contents': '',
  'POST /files/upload/start': '',
  'POST /files/upload/end': DataUploadIcon,
  'POST /datalinks': '',
  'GET /datalinks/{DATALINK_ID}': '',
  'DELETE /datalinks/{DATALINK_ID}': '',
  'POST /directories': '',
  'GET /directories/{DIRECTORY_ID}': '',
  'PUT /directories/{DIRECTORY_ID}': '',
  'DELETE /directories/{DIRECTORY_ID}': '',
  'POST /secrets': '',
  'GET /secrets': KeyIcon,
  'GET /secrets/{SECRET_ID}': KeyIcon,
  'PUT /secrets/{SECRET_ID}': '',
  'DELETE /secrets/{SECRET_ID}': '',
  'POST /configurations': '',
  'GET /configurations': '',
  'GET /configurations/{CONFIGURATION_ID}': '',
  'GET /path/resolve': '',
}

export const EVENT_TYPE_NAME_ID: Record<LambdaKind, TextId & `${string}LogEvent`> = {
  'POST /auth': 'authLogEvent',
  'GET /organizations/me': 'getOrganizationLogEvent',
  'PATCH /organizations/me': 'updateOrganizationLogEvent',
  'PUT /organizations/me/picture': 'uploadOrganizationPictureLogEvent',
  'POST /logs': 'postLogEventLogEvent',
  'GET /invitations': 'listInvitationsLogEvent',
  'DELETE /invitations': 'deleteInvitationLogEvent',
  'POST /payments/subscriptions': 'createSubscriptionLogEvent',
  'GET /payments/subscriptions/{SUBSCRIPTION_ID}': 'getSubscriptionLogEvent',
  'DELETE /payments/subscriptions/{SUBSCRIPTION_ID}': 'deleteSubscriptionLogEvent',
  'GET /usergroups': 'listUserGroupsLogEvent',
  'POST /usergroups': 'createUserGroupLogEvent',
  'DELETE /usergroups/{USER_GROUP_ID}': 'deleteUserGroupLogEvent',
  'GET /users': 'listUsersLogEvent',
  'POST /users': 'createUserLogEvent',
  'POST /users/invite': 'inviteUserLogEvent',
  'GET /users/me': 'getSelfUserLogEvent',
  'PUT /users/me': 'updateSelfUserLogEvent',
  'DELETE /users/me': 'deleteSelfUserLogEvent',
  'PUT /users/me/picture': 'uploadSelfUserPictureLogEvent',
  'PUT /users/{USER_ID}/usergroups': 'updateUserUserGroupsLogEvent',
  'GET /tags': 'listLabelsLogEvent',
  'POST /tags': 'createLabelLogEvent',
  'DELETE /tags/{TAG_ID}': 'deleteLabelLogEvent',
  'GET /log_events': 'listLogEventsLogEvent',
  'PATCH /assets': 'undoDeleteAssetLogEvent',
  'DELETE /assets/{ASSET_ID}': 'deleteAssetLogEvent',
  'POST /assets/{ASSET_ID}/copy': 'copyAssetLogEvent',
  'PATCH /assets/{ASSET_ID}': 'updateAssetLogEvent',
  'PATCH /assets/{ASSET_ID}/labels': 'updateAssetLabelsLogEvent',
  'PATCH /assets/{ASSET_ID}/touch': 'touchAssetLogEvent',
  'GET /assets/{ASSET_ID}/versions': 'listAssetVersionsLogEvent',
  'POST /assets/{ASSET_ID}/versions/restore': 'rewindAssetLogEvent',
  'POST /permissions': 'createPermissionLogEvent',
  'POST /projects': 'createProjectLogEvent',
  'GET /projects/{PROJECT_ID}': 'getProjectDetailsLogEvent',
  'PUT /projects/{PROJECT_ID}': 'updateProjectLogEvent',
  'GET /projects/{PROJECT_ID}/contents': 'getProjectContentsLogEvent',
  'GET /projects/{PROJECT_ID}/files': 'getProjectFilesLogEvent',
  'POST /projects/{PROJECT_ID}/open': 'openProjectLogEvent',
  'POST /projects/{PROJECT_ID}/close': 'closeProjectLogEvent',
  'POST /projects/{PROJECT_ID}/upload': 'updateProjectFilesLogEvent',
  'POST /projects/{PROJECT_ID}/versions/restore': 'rewindProjectLogEvent',
  'POST /projects/{PROJECT_ID}/versions/clone': 'cloneProjectLogEvent',
  'POST /projects/{PROJECT_ID}/hybrid_set_opened': 'setHybridOpenedLogEvent',
  'POST /projects/{PROJECT_ID}/hybrid_set_open_in_progress': 'setHybridOpenInProgressLogEvent',
  'GET /projects/{PROJECT_ID}/executions': 'listProjectExecutionsLogEvent',
  'POST /projects/{PROJECT_ID}/executions/new': 'createProjectExecutionLogEvent',
  'GET /project-sessions': 'listProjectSessionsLogEvent',
  'GET /project-sessions/{PROJECT_SESSION_ID}/logs': 'getProjectSessionLogsLogEvent',
  'GET /executions/{EXECUTION_ID}': 'getExecutionLogEvent',
  'DELETE /executions/{EXECUTION_ID}': 'deleteExecutionLogEvent',
  'POST /files': 'createFileLogEvent',
  'GET /files': 'listFilesLogEvent',
  'GET /files/{FILE_ID}': 'getFileDetailsLogEvent',
  'GET /files/{FILE_ID}/contents': 'getFileContentsLogEvent',
  'POST /files/upload/start': 'uploadFileStartLogEvent',
  'POST /files/upload/end': 'uploadFileEndLogEvent',
  'POST /datalinks': 'createDatalinkLogEvent',
  'GET /datalinks/{DATALINK_ID}': 'getDatalinkLogEvent',
  'DELETE /datalinks/{DATALINK_ID}': 'deleteDatalinkLogEvent',
  'POST /directories': 'createDirectoryLogEvent',
  'GET /directories/{DIRECTORY_ID}': 'getDirectoryLogEvent',
  'PUT /directories/{DIRECTORY_ID}': 'updateDirectoryLogEvent',
  'DELETE /directories/{DIRECTORY_ID}': 'deleteDirectoryLogEvent',
  'POST /secrets': 'createSecretLogEvent',
  'GET /secrets': 'listSecretsLogEvent',
  'GET /secrets/{SECRET_ID}': 'getSecretLogEvent',
  'PUT /secrets/{SECRET_ID}': 'updateSecretLogEvent',
  'DELETE /secrets/{SECRET_ID}': 'deleteSecretLogEvent',
  'POST /configurations': 'createConfigurationLogEvent',
  'GET /configurations': 'listConfigurationsLogEvent',
  'GET /configurations/{CONFIGURATION_ID}': 'getConfigurationLogEvent',
  'GET /path/resolve': 'resolvePathLogEvent',
}
/* eslint-enable @typescript-eslint/naming-convention */
