pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "label=CI: Ready to merge"
    actions:
      merge:
        method: squash
        commit_message_template: |
          {{ title }} (#{{ number }})
          {{ body | get_section("### Pull Request Description", "") }}

          {% set notes = body | get_section("### Important Notes", "") -%}
          {%- if notes -%}
          # Important Notes
          {{ notes }}
          {%- endif -%}
  - name: Automatic PR update
    conditions:
      - or:
          - "label=CI: Keep up to date"
    actions:
      update:
