#!/usr/bin/env python3

import os
import subprocess
import sys
import traceback

from config.build import stack_build

def main ():
    try:
        stack_build.run()
    except:
        traceback.print_exc()
        print('Status : FAIL')
        sys.exit(1)
    else:
        print('Status: DONE')

if __name__ == '__main__':
    main()

