#!/usr/bin/env python3

import scripts_build.stack_build
import os
import subprocess



def main ():
    try:
        scripts_build.stack_build.run()
        
    except subprocess.CalledProcessError:
        print("Status : FAIL")


main()
