author: Wojciech Danilo
benchmarks:
  layered-state-benchmark:
    dependencies: [criterion, layered-state, mtl-c, kan-extensions, deepseq, timeit,
      either]
    main: Main.hs
    source-dirs: test/bench
bug-reports: https://github.com/wdanilo/layered-state/issues
category: Data
copyright: Copyright (C) 2015 Wojciech Danilo
default-extensions: [ConstraintKinds, DataKinds, DefaultSignatures, DeriveDataTypeable,
  DeriveFoldable, DeriveFunctor, DeriveGeneric, DeriveTraversable, DoAndIfThenElse,
  EmptyDataDecls, FlexibleContexts, FlexibleInstances, GeneralizedNewtypeDeriving,
  InstanceSigs, LambdaCase, MultiParamTypeClasses, NoImplicitPrelude, OverloadedStrings,
  StandaloneDeriving, TemplateHaskell, TupleSections, TypeApplications, TypeOperators,
  UnicodeSyntax, ViewPatterns, TypeFamilies]
dependencies: [base, lens, mtl, primitive, exceptions, prologue, constraints, data-default,
  transformers, typelevel, lens-utils, monad-branch, monoid, profunctors]
ghc-options: [-Wall, -O2]
homepage: https://github.com/wdanilo/layered-state
library: {source-dirs: src}
license: Apache-2.0
maintainer: Wojciech Danilo <wojciech.danilo@gmail.com>
name: layered-state
stability: experimental
synopsis: Control structure similar to Control.Monad.State, allowing multiple nested
  states, distinguishable by provided phantom types.
version: '1.0'
