max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Max"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
match_arm_leading_pipes = "Never"
fn_params_layout = "Tall"
match_block_trailing_comma = false
edition = "2021"
merge_derives = false
use_try_shorthand = false
use_field_init_shorthand = true
force_explicit_abi = true
disable_all_formatting = false
