[package]
name = "enso-formatter"
version = "0.1.0"
authors = ["Enso Team <contact@enso.org>"]
edition = "2021"

[dependencies]
regex = { workspace = true }
ide-ci = { path = "../ci_utils" }
tokio = { workspace = true }

[lints]
workspace = true
