//! Traits providing abstraction over transport used by the JSON-RPC client.

use prelude::*;

use failure::Error;

/// A transport that facilitate JSON-RPC protocol.
///
/// Must allow sending and receiving text messages. Additionally, connection at
/// any point might be lost for any reason.
///
/// Typical implementation would use WebSockets but it can be also a mock for
/// tests.
pub trait Transport : Debug {
    /// Send a text message.
    fn send_text(&mut self, message:String) -> Result<(), Error>;

    /// Set a callback that gets notified on transport events.
    fn set_event_tx(&mut self, tx:std::sync::mpsc::Sender<TransportEvent>);
}

impl<T: Transport> Transport for Rc<RefCell<T>> {
    fn send_text(&mut self, message:String) -> Result<(), Error> {
        self.borrow_mut().send_text(message)
    }
    fn set_event_tx(&mut self, tx:std::sync::mpsc::Sender<TransportEvent>) {
        self.borrow_mut().set_event_tx(tx)
    }
}

/// An event generated by the `Transport`.
#[derive(Debug)]
pub enum TransportEvent {
    /// A text message with has been received.
    TextMessage(String),
    /// A socket has been closed by the peer.
    Closed,
}
