use std::fs;
use serde_yaml;
use serde_yaml::Value;
use inflector::*;

const CONFIG_PATH : &str = "../../../config.yaml";

fn main() {
    println!("cargo:rerun-if-changed={}",CONFIG_PATH);
    println!("cargo:rerun-if-changed=build.rs");

    let f = std::fs::File::open(CONFIG_PATH).unwrap();
    let value: Value = serde_yaml::from_reader(f).unwrap();

    let indent   = " ".repeat(4);
    let mut def  = "".to_string();
    let mut inst = "".to_string();
    let mut vars = "".to_string();
    match value {
        Value::Mapping(mapping) => {
            for (key,value) in mapping {
                let key = key.as_str().unwrap().to_snake_case();
                let value = value.as_str().unwrap();
                def.push_str(&format!("{}pub {} : &'static str,\n",indent,key));
                inst.push_str(&format!("{}{} : \"{}\",\n",indent,key,value));
                vars.push_str(&format!("pub const {} : &str = \"{}\";\n",key,value));
            }
        }
        _ => panic!("Unexpected config format.")
    }

    let header = format!("// THIS IS AN AUTOGENERATED FILE BASED ON THE '{}' CONFIG FILE. \
                             DO NOT MODIFY IT.",CONFIG_PATH);
    let pragmas    = format!("#![allow(non_upper_case_globals)]");
    let struct_def = format!("pub struct Config {{\n{}}}",def);
    let const_def  = format!("pub const CONFIG : Config = Config {{\n{}}};",inst);
    let file        = format!("{}\n\n{}\n\n{}\n\n{}\n\n{}",header,pragmas,struct_def,const_def,vars);
    fs::write("src/autogenerated.rs",file).ok();
}
