package org.enso.interpreter.dsl.test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

import com.oracle.truffle.api.dsl.UnsupportedSpecializationException;
import java.util.List;
import java.util.function.Supplier;
import org.enso.interpreter.EnsoLanguage;
import org.enso.interpreter.runtime.callable.function.Function;
import org.enso.interpreter.runtime.data.text.Text;
import org.enso.interpreter.runtime.error.DataflowError;
import org.enso.interpreter.runtime.error.PanicException;
import org.enso.test.utils.ContextUtils;
import org.junit.Rule;
import org.junit.Test;

/**
 * Most of the exceptions thrown by the builtin methods, generated by {@link
 * org.enso.interpreter.dsl.impl.MethodProcessor}, should not be caught. Only a specific subset of
 * exceptions, that we can handle, should be caught, and converted to either a {@link
 * PanicException}, or to {@link DataflowError}.
 *
 * <p>These tests checks this contract.
 */
public class ThrowableCatchTest {
  @Rule public final ContextUtils ctxRule = ContextUtils.createDefault();

  private static List<Class<?>> shouldBeHandledExceptionTypes =
      List.of(UnsupportedSpecializationException.class);

  static List<Supplier<Error>> errorSuppliers =
      List.of(
          () -> new Error("First error"),
          () -> new AssertionError("Assertion error"),
          CustomError::new);

  private static class CustomError extends Error {}

  @Test
  public void testMostErrorsCanPropagateFromBuiltinMethods() {
    var func = ThrowBuiltinMethodGen.makeFunction(EnsoLanguage.get(null));
    var funcCallTarget = func.getCallTarget();
    for (long errorSupplierIdx = 0; errorSupplierIdx < errorSuppliers.size(); errorSupplierIdx++) {
      Object self = null;
      Object[] args =
          Function.ArgumentsHelper.buildArguments(
              func, null, new Object[] {self, Text.create("error"), errorSupplierIdx});
      try {
        funcCallTarget.call(args);
      } catch (Throwable t) {
        var expectedError = errorSuppliers.get((int) errorSupplierIdx).get();
        if (shouldExceptionBeHandled(t)) {
          expectPanicOrDataflowErrorWithMessage(t, expectedError.getMessage());
        } else {
          assertSameExceptions(
              "Thrown RuntimeException should not be modified in the builtin method",
              expectedError,
              t);
        }
      }
    }
  }

  private void assertSameExceptions(String msg, Throwable expected, Throwable actual) {
    assertEquals(msg, expected.getClass(), actual.getClass());
    assertEquals(msg, expected.getMessage(), actual.getMessage());
  }

  private static boolean shouldExceptionBeHandled(Throwable t) {
    return shouldBeHandledExceptionTypes.stream()
        .anyMatch(exceptionType -> exceptionType.isInstance(t));
  }

  private void expectPanicOrDataflowErrorWithMessage(Throwable t, String expectedMsg) {
    if (t instanceof PanicException panic) {
      assertEquals(expectedMsg, panic.getMessage());
    } else if (t instanceof DataflowError dataflowError) {
      assertEquals(expectedMsg, dataflowError.getMessage());
    } else {
      fail("Should throw only PanicException or DataflowError: " + t.getMessage());
    }
  }
}
