load("@aspect_rules_esbuild//esbuild:defs.bzl", "esbuild")
load("@aspect_rules_js//npm:defs.bzl", "npm_package")
load("@aspect_rules_ts//ts:defs.bzl", "ts_config", "ts_project")
load("@npm//:defs.bzl", "npm_link_all_packages", "npm_link_targets")
load("@npm//app/electron-client:electron-builder/package_json.bzl", electron_builder_bin = "bin")

npm_link_all_packages(name = "node_modules")

ts_config(
    name = "tsconfig",
    src = "tsconfig.json",
    visibility = [":__subpackages__"],
    deps = ["//:tsconfig"],
)

ts_project(
    name = "tsc",
    srcs = glob(["src/*.ts"]),
    composite = True,
    declaration = True,
    resolve_json_module = True,
    source_map = True,
    tsconfig = "//app/project-manager-shim:tsconfig",
    validate = select({
        "@platforms//os:windows": False,
        "//conditions:default": True,
    }),
    visibility = ["//visibility:public"],
    deps = ["//:tsconfig"] + npm_link_targets(),
)

npm_package(
    name = "package",
    srcs = [":tsc"],
    include_runfiles = False,
    visibility = ["//visibility:public"],
)

esbuild(
    name = "bundle",
    srcs = glob(["src/**/*.ts"]) + [
        "buildInfo.ts",
        "fileAssociations.ts",
        "paths.ts",
    ],
    bundle = True,
    config = ":esbuild.config.mjs",
    entry_points = [
        "src/index.ts",
        "src/preload.ts",
    ],
    external = [
        "electron",
        "vite",
        "lightningcss",
        "bufferutil",
        "utf-8-validate",
        "encoding",
    ],
    output_dir = True,
    sourcemap = "linked",
    visibility = ["//visibility:public"],
    deps = npm_link_targets(),
)

electron_builder_bin.electron_builder(
    name = "electron_builder_run",
    srcs = npm_link_targets() + [
        "package.json",
        ":electron-builder-config.cjs",
        "//:sbt_build_engine_distribution",
        "//:sbt_build_small_jdk",
    ] + [
        ":bundle",
        "//app/gui:dist",
    ],
    args = [
        "build",
        "--config electron-builder-config.cjs",
    ],
    chdir = package_name(),
    env = {
        # Disable Node fs patching for this target to avoid readlink issues on Bazel bin symlinks.
        "JS_BINARY__PATCH_NODE_FS": "0",
    },
    # Run from BINDIR (default); rely on package.json "build" config.
    out_dirs = ["ide-dist"],
    visibility = ["//visibility:public"],
)
