_config/lib: !include "../../../config/hpack-common.yaml"

name       : luna-syntax-text-builder
version    : "0.2"
author     : Luna Team <contact@luna-lang.org>
maintainer:
    - Wojciech Danilo  <wojciech.danilo@luna-lang.org>
    - Marcin Kostrzewa <marcin.kostrzewa@luna-lang.org>
    - Ara Adkins       <ara.adkins@luna-lang.org>

library:
    source-dirs:
        - src

tests:
    spec:
        main: Main.hs
        source-dirs: test/spec
        dependencies:
            - container
            - directory
            - filepath
            - hspec
            - hspec-expectations-lifted
            - hspec-megaparsec
            - luna-core
            - luna-syntax-text-builder
            - luna-syntax-text-lexer
            - luna-syntax-text-parser
            - luna-syntax-text-prettyprint
            - open-browser
            - template-haskell

dependencies:
    - attoparsec
    - base
    - containers
    - layered-state
    - layouting
    - lens
    - lens-utils
    - luna-core
    - luna-cpp-containers
    - luna-data-storable
    - luna-foreign-utils
    - luna-generic-traversable
    - luna-nested-containers
    - luna-parser-utils
    - luna-syntax-definition
    - luna-syntax-text-lexer
    - luna-syntax-text-parser
    - luna-syntax-text-model
    - luna-text-processing
    - luna-typelevel
    - megaparsec
    - mtl
    - prologue
    - text
    - vector
    - vector-text

default-extensions: *luna-extensions

