extra-deps: [error-util-0.0.1.1, cond-0.4.1.1, ghc-mtl-1.2.1.0, serialport-0.4.7,
  hspec-jenkins-0.1.1, hspec-2.2.4, hspec-core-2.2.4, hspec-discover-2.2.4, hspec-expectations-0.7.2,
  HUnit-1.3.1.2, containers-0.5.8.2, ansi-terminal-0.6.3.1]
ghc-options: {'*': -fenable-rewrite-rules -threaded -funbox-strict-fields -fconstraint-solver-iterations=100}
packages:
- {location: .}
- extra-dep: true
  location: {commit: 6c291bc4791cba364ce5763eda98292c96b66019, git: 'https://github.com/luna/container.git'}
- extra-dep: true
  location: {commit: 4cc75aeb82ad2885427211a1be9cb0c7d9582c01, git: 'https://github.com/luna/data-pool.git'}
- extra-dep: true
  location: {commit: 4faf74827396aca2ab65a76d28cddc1ecb2f70d2, git: 'https://github.com/luna/convert.git'}
- extra-dep: true
  location: {commit: a81f2eb37b0bddbc3391c8a29860b921aa94f3c8, git: 'https://github.com/luna/data-base.git'}
- extra-dep: true
  location: {commit: a6afda3b96efe00938aba61ac12a2f5f2134ff3d, git: 'https://github.com/luna/data-construction.git'}
- extra-dep: true
  location: {commit: 8a5773adba33d71a311ba0b4123b744213b0be91, git: 'https://github.com/luna/data-layer.git'}
- extra-dep: true
  location: {commit: 9da4c9b2534693cfe82adeb37f12eaadacb41e62, git: 'https://github.com/luna/data-repr.git'}
- extra-dep: true
  location: {commit: 71e17fc7e1b1ac3e5801042b2c99a6f6ad82df3c, git: 'https://github.com/luna/data-result.git'}
- extra-dep: true
  location: {commit: 71a26613c43f76c3f5b61dc99046262065b91694, git: 'https://github.com/luna/dependent-state.git'}
- extra-dep: true
  location: {commit: 1c6a4fd165e4b15cad114b0a554e0974fd119223, git: 'https://github.com/luna/functor-utils.git'}
- extra-dep: true
  location: {commit: a1606cccc12cb521acbc598e52c481b9054b42a7, git: 'https://github.com/luna/impossible.git'}
- extra-dep: true
  location: {commit: b45aacbf536194bee5a3c6041231fde1dabdc8fe, git: 'https://github.com/luna/lens-utils.git'}
- extra-dep: true
  location: {commit: 965e23539a001517994398ae02421334bf77c6e6, git: 'https://github.com/luna/poly-control.git'}
- extra-dep: true
  location: {commit: d7dc75913103ff15e79d8e7b377b89cb49ae925b, git: 'https://github.com/luna/prologue.git'}
- extra-dep: true
  location: {commit: f4292663aea639c17f66ba3d67e09c79ebf62982, git: 'https://github.com/luna/type-cache.git'}
- extra-dep: true
  location: {commit: 107db9368e95e192d70c0dec274ecfe3592101d2, git: 'https://github.com/luna/typelevel.git'}
- extra-dep: true
  location: {commit: a6afda3b96efe00938aba61ac12a2f5f2134ff3d, git: 'https://github.com/luna/data-construction.git'}
- extra-dep: true
  location: {commit: b5f02ced2912501d923c07950789fbcf44a6a9ce, git: 'https://github.com/luna/data-prop.git'}
- extra-dep: true
  location: {commit: 5307f2e636fa9b80d991df183f7a594948ad2ad1, git: 'https://github.com/luna/data-rtuple.git'}
- extra-dep: true
  location: {commit: d0fe8fe9ffc82e57058e3119fa4bed6f307df2de, git: 'https://github.com/luna/data-shell.git'}
- extra-dep: true
  location: {commit: ddfcd1e0372b93e947b380b911c123fe67227b21, git: 'https://github.com/luna/visualization-api.git'}
- extra-dep: true
  location: {commit: e63e373d67cd8dd7c179a618f5d32f6ffb3abdd3, git: 'https://github.com/luna/monoid'}
- extra-dep: true
  location: {commit: 19cd9bd99caf29424def070783526335ee5bff8a, git: 'https://github.com/luna/text-processing'}
- extra-dep: true
  location: {commit: c028e7939bf79853e63bc40f2576d9280dffbb4c, git: 'https://github.com/luna/terminal-text'}
resolver: lts-8.2
