import org.apache.commons.io.FileUtils
import sbt.*
import sbt.Keys.*
import scala.jdk.CollectionConverters.collectionAsScalaIterableConverter

/** Basic support for Bazel, more specifically, being able to run `sbt` from bazel.
  * Ultimately, we would like to migrate the whole project to Bazel.
  * In the meantime, let's respect that the build entrypoint is bazel, and not sbt.
  *
  * All the Bazel-related settings are "hidden" inside `Bazel` configuration.
  *
  * If sbt is running from within bazel (i.e. as a subprocess of bazel), we cannot run
  * for example `cargo` or `pnpm` subprocesses from sbt.
  *
  * The basic support for Bazel was added in https://github.com/enso-org/enso/pull/13239
  */
object BazelSupport extends AutoPlugin {
  val ENABLED_PROP                    = "enso.BazelSupport.enabled"
  val HOME_DIR_PROP                   = "enso.BazelSupport.home"
  val OUT_DIR_PROP                    = "enso.BazelSupport.outDir"
  val RUST_PARSER_JAVA_SRC_DIR_PROP   = "enso.BazelSupport.parser.javaSrcDir"
  val RUST_PARSER_LIB_PROP            = "enso.BazelSupport.parser.lib"
  val EXTRACTED_PYTHON_RESOURCES_PROP = "enso.BazelSupport.python.resourceDir"
  val YDOC_SERVER_POLYGLOT_MAIN_JS =
    "enso.BazelSupport.ydocServer.polyglotMainJs"
  val C_LIBS_PATH = "enso.BazelSupport.CLibraryPath"

  object autoImport {
    lazy val wasStartedFromBazel = settingKey[Boolean](
      "True if sbt process was started as bazel's subprocess"
    )
    lazy val homeDir = settingKey[Option[File]](
      "Path to $HOME directory. This is necessary to set because it is expected " +
      "by various components when for example compiling standard libraries. " +
      "Note that Bazel is not able to give us an absolute path to a directory inside a sandbox, " +
      "so we resolve the relative path in sbt."
    )
    lazy val outputDir = settingKey[Option[File]](
      """
        |Path to the output directory for the distribution.
        |In non-bazel build, it is set to `built-distribution` in repo root.
        |""".stripMargin
    )
    lazy val rustParserJavaSources = taskKey[Seq[File]](
      "Java sources generated by the Rust parser"
    )
    lazy val rustParserJavaSourceDir = settingKey[File](
      "Directory containing Java sources generated by the Rust parser"
    )
    lazy val rustParserLib = taskKey[File](
      "Rust native parser DLL"
    )
    lazy val extractedPythonResourceDir = taskKey[File](
      "Directory containing extracted Python resources"
    )
    lazy val cLibraryPath = taskKey[Option[File]](
      "Path to the C libraries. Will be passed to native-image via `-H:CLibraryPath`."
    )
    lazy val ydocServerPolyglotMainJs = taskKey[File](
      "Path to the ydoc-server polyglot main JS file."
    )
    lazy val Bazel = config("Bazel")
  }

  import autoImport._

  override def projectConfigurations: Seq[Configuration] = {
    Seq(
      Bazel
    )
  }

  override lazy val globalSettings: Seq[Setting[_]] = {
    Bazel / wasStartedFromBazel := {
      System.getProperty(ENABLED_PROP) != null
    }
  }

  override lazy val buildSettings: Seq[Setting[_]] = {
    Seq(
      Bazel / homeDir := {
        val prop = System.getProperty(HOME_DIR_PROP)
        if (prop == null) {
          None
        } else {
          val home = new File(prop)
          if (!home.exists()) {
            IO.createDirectory(home)
          }
          Some(home)
        }
      },
      Bazel / outputDir := {
        val prop = System.getProperty(OUT_DIR_PROP)
        if (prop == null) {
          None
        } else {
          val outDir = new File(prop)
          if (!outDir.exists()) {
            IO.createDirectory(outDir)
          }
          Some(outDir)
        }
      },
      Bazel / rustParserJavaSourceDir := {
        val prop = System.getProperty(RUST_PARSER_JAVA_SRC_DIR_PROP)
        if (prop != null) {
          new File(prop)
        } else {
          // We don't care if the file does not exist. If the prop is not set,
          // it should not be used at all.
          new File("FOO")
        }
      },
      Bazel / rustParserJavaSources := {
        val logger = streams.value.log
        val srcDir = (Bazel / rustParserJavaSourceDir).value
        if (!srcDir.exists()) {
          logger.warn(
            s"Rust parser Java sources not found at $srcDir. " +
            "Make sure to generate the Java sources with `bazel build //lib/rust/parser:generate_java`." +
            "Passed via system property " + RUST_PARSER_JAVA_SRC_DIR_PROP + "."
          )
        }
        FileUtils.listFiles(srcDir, Array("java"), true).asScala.toSeq
      },
      Bazel / rustParserLib := {
        val logger = streams.value.log
        val prop   = System.getProperty(RUST_PARSER_LIB_PROP)
        if (prop == null) {
          logger.error(
            s"Rust parser library not set in ${RUST_PARSER_LIB_PROP} property."
          )
        }
        val parserLib = new File(prop)
        if (!parserLib.exists()) {
          logger.warn(
            s"Rust parser library not found at $parserLib. " +
            "Make sure to build the parser with `bazel build //lib/rust/parser:enso_parser`."
          )
        }
        parserLib
      },
      Bazel / extractedPythonResourceDir := {
        val logger = streams.value.log
        val prop   = System.getProperty(EXTRACTED_PYTHON_RESOURCES_PROP)
        if (prop == null) {
          logger.error(
            s"Extracted Python resources directory not set in ${EXTRACTED_PYTHON_RESOURCES_PROP} property."
          )
        }
        val dir = new File(prop)
        if (!dir.exists()) {
          logger.warn(
            s"Extracted Python resources directory not found at $dir. " +
            "Make sure to extract the resources with `bazel build //lib/java/python-extract:extract_python_resources`."
          )
        }
        dir
      },
      Bazel / ydocServerPolyglotMainJs := {
        val logger = streams.value.log
        val prop   = System.getProperty(YDOC_SERVER_POLYGLOT_MAIN_JS)
        if (prop == null) {
          logger.error(
            s"Ydoc-server polyglot main JS not set in ${YDOC_SERVER_POLYGLOT_MAIN_JS} property."
          )
        }
        val jsFile = new File(prop)
        if (!jsFile.exists()) {
          logger.warn(
            s"Ydoc-server polyglot main JS not found at $jsFile. " +
            "Make sure to build it with `bazel build //app/ydoc-server-polyglot:dist`."
          )
        }
        jsFile
      },
      Bazel / cLibraryPath := {
        val logger = streams.value.log
        Option(System.getProperty(C_LIBS_PATH)).map(new File(_)).flatMap {
          lib =>
            if (lib.exists()) Some(lib)
            else {
              logger.error(
                s"C Library not found at $lib. " +
                "Make sure to provide a valid C Library."
              )
              None
            }
        }
      }
    )
  }
}
