import org.apache.commons.io.FileUtils
import sbt.*
import sbt.Keys.*

import scala.jdk.CollectionConverters.collectionAsScalaIterableConverter

/** Basic support for Bazel, more specifically, being able to run `sbt` from bazel.
  * Ultimately, we would like to migrate the whole project to Bazel.
  * In the meantime, let's respect that the build entrypoint is bazel, and not sbt.
  *
  * All the Bazel-related settings are "hidden" inside `Bazel` configuration.
  *
  * If sbt is running from within bazel (i.e. as a subprocess of bazel), we cannot run
  * for example `cargo` or `pnpm` subprocesses from sbt.
  *
  * The basic support for Bazel was added in https://github.com/enso-org/enso/pull/13239
  */
object BazelSupport extends AutoPlugin {
  val ENABLED_PROP                  = "enso.BazelSupport.enabled"
  val HOME_DIR_PROP                 = "enso.BazelSupport.home"
  val RUST_PARSER_JAVA_SRC_DIR_PROP = "enso.BazelSupport.parser.javaSrcDir"
  val RUST_PARSER_LIB_PROP          = "enso.BazelSupport.parser.lib"

  object autoImport {
    lazy val wasStartedFromBazel = settingKey[Boolean](
      "True if sbt process was started as bazel's subprocess"
    )

    lazy val homeDir = settingKey[Option[File]](
      "Path to $HOME directory. This is necessary to set because it is expected " +
      "by various components when for example compiling standard libraries. " +
      "Note that Bazel is not able to give us an absolute path to a directory inside a sandbox, " +
      "so we resolve the relative path in sbt."
    )

    lazy val rustParserJavaSources = taskKey[Seq[File]](
      "Java sources generated by the Rust parser"
    )

    lazy val rustParserJavaSourceDir = settingKey[File](
      "Directory containing Java sources generated by the Rust parser"
    )

    lazy val rustParserLib = taskKey[File](
      "Rust native parser DLL"
    )

    lazy val Bazel = config("Bazel")
  }

  import autoImport._

  override def projectConfigurations: Seq[Configuration] = {
    Seq(
      Bazel
    )
  }

  override lazy val globalSettings: Seq[Setting[_]] = {
    Bazel / wasStartedFromBazel := {
      System.getProperty(ENABLED_PROP) != null
    }
  }

  override lazy val buildSettings: Seq[Setting[_]] = {
    Seq(
      Bazel / homeDir := {
        val prop = System.getProperty(HOME_DIR_PROP)
        if (prop == null) {
          None
        } else {
          val home = new File(prop)
          if (!home.exists()) {
            IO.createDirectory(home)
          }
          Some(home)
        }
      },
      Bazel / rustParserJavaSourceDir := {
        val prop = System.getProperty(RUST_PARSER_JAVA_SRC_DIR_PROP)
        if (prop != null) {
          new File(prop)
        } else {
          // We don't care if the file does not exist. If the prop is not set,
          // it should not be used at all.
          new File("FOO")
        }
      },
      Bazel / rustParserJavaSources := {
        val logger = streams.value.log
        val srcDir = (Bazel / rustParserJavaSourceDir).value
        if (!srcDir.exists()) {
          logger.warn(
            s"Rust parser Java sources not found at $srcDir. " +
            "Make sure to generate the Java sources with `bazel build //lib/rust/parser:generate_java`." +
            "Passed via system property " + RUST_PARSER_JAVA_SRC_DIR_PROP + "."
          )
        }
        FileUtils.listFiles(srcDir, Array("java"), true).asScala.toSeq
      },
      Bazel / rustParserLib := {
        val logger = streams.value.log
        val prop   = System.getProperty(RUST_PARSER_LIB_PROP)
        if (prop == null) {
          logger.error(
            s"Rust parser library not set in ${RUST_PARSER_LIB_PROP} property."
          )
        }
        val parserLib = new File(prop)
        if (!parserLib.exists()) {
          logger.warn(
            s"Rust parser library not found at $parserLib. " +
            "Make sure to build the parser with `bazel build //lib/rust/parser:enso_parser`."
          )
        }
        parserLib
      }
    )
  }
}
