addSbtPlugin("com.eed3si9n"       % "sbt-assembly"             % "0.14.10")
addSbtPlugin("ch.epfl.scala"      % "sbt-bloop"                % "1.4.0-RC1")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.0.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.1.0")
addSbtPlugin("com.typesafe.sbt"   % "sbt-license-report"       % "1.2.0")
