import sbt.Keys.*
import sbt.*
import sbt.internal.util.ManagedLogger
import sbt.io.IO
import sbt.librarymanagement.{ConfigurationFilter, DependencyFilter}
import sbt.util.CacheStoreFactory

import java.io.{File, IOException}
import java.nio.file.Path
import java.util.Locale

object StdBits {

  /** Discovers dependencies of a project and copies them into the destination
    * directory.
    *
    * @param destination location where to put the dependencies
    * @param providedJarNames name of JARs generated by the local projects;
    *                         unexpected (old) files are removed, so this task
    *                         needs to know these files' names to avoid removing
    *                         them
    * @param ignoreScalaLibrary whether to ignore Scala dependencies that are
    *                           added by default be SBT and are not relevant in
    *                           pure-Java projects
    * @param libraryUpdates resolution report
    * @param unmanagedClasspath classpath of unmanaged jars, if any
    * @param logger SBT's logger
    * @param cacheStoreFactory SBT's cache sotre factory
    * @param ignoreDependenciesByModuleID Depedencies that should be ignored - not copied to the destination
    * @param ignoreDependencies Depedencies that should be ignored based on a plain file name filter
    * @param ignoreDependencyIncludeTransitive An optional filter to indicate that a direct dependency should be ignored except for its (transitive) dependencies
    * @param ignoreUnmanagedDependency An optional filter that tests if an unmanaged dependency should be ignored
    *
    * @param previousRun summary of previous extraction data, if available
    */
  def copyDependencies(
    destination: File,
    providedJarNames: Seq[String],
    ignoreScalaLibrary: Boolean,
    libraryUpdates: UpdateReport,
    unmanagedClasspath: Classpath,
    logger: ManagedLogger,
    cacheStoreFactory: sbt.util.CacheStoreFactory,
    ignoreDependenciesByModuleID: Option[Seq[ModuleID]] = None,
    ignoreDependencies: Option[String => Boolean]       = None,
    ignoreDependencyIncludeTransitive: Option[String]   = None,
    ignoreUnmanagedDependency: Option[File => Boolean]  = None,
    previousRun: Option[AnalysisOfExtractedNativeLibs]  = None
  ): Unit = {

    val baseFilter: NameFilter = new ExactFilter(Configurations.Runtime.name)
    val validConfig =
      if (ignoreScalaLibrary)
        baseFilter - new ExactFilter(Configurations.ScalaTool.name)
      else baseFilter
    val configFilter: ConfigurationFilter =
      DependencyFilter.configurationFilter(name = validConfig)
    val graalVmOrgs = if ("espresso".equals(System.getenv("ENSO_JAVA"))) {
      Seq()
    } else {
      GraalVM.modules.map(_.organization).distinct
    }
    // All graal related modules must be filtered away - they will be provided in
    // module-path, and so, they must not be included in std-bits polyglot directories.
    val graalModuleFilter = DependencyFilter.moduleFilter(
      organization = new SimpleFilter(!graalVmOrgs.contains(_))
    )
    val moduleFilter = ignoreDependenciesByModuleID match {
      case None => graalModuleFilter
      case Some(ignoreDepIDs) =>
        DependencyFilter.moduleFilter(
          organization = new SimpleFilter(orgName =>
            !graalVmOrgs.contains(
              orgName
            )
          ),
          name = new SimpleFilter(name => !ignoreDepIDs.exists(_.name == name))
        )
    }
    val unmanagedFiles0 = unmanagedClasspath.map(_.data)
    val unmanagedFiles = ignoreUnmanagedDependency
      .map(fun => unmanagedFiles0.filterNot(fun))
      .getOrElse(unmanagedFiles0)
    val relevantFiles0 =
      libraryUpdates
        .select(
          configuration = configFilter,
          module        = moduleFilter,
          artifact      = DependencyFilter.artifactFilter()
        ) ++ unmanagedFiles
    val relevantFiles1 =
      ignoreDependencyIncludeTransitive
        .map(filter => relevantFiles0.filterNot(_.getName.contains(filter)))
        .getOrElse(relevantFiles0)
    val relevantFiles =
      ignoreDependencies
        .map(filter => relevantFiles1.filterNot(f => filter(f.getName)))
        .getOrElse(relevantFiles1)
    val dependencyStore =
      cacheStoreFactory.make("std-bits-dependencies")
    Tracked.diffInputs(dependencyStore, FileInfo.hash)(relevantFiles.toSet) {
      report =>
        val expectedFileNames =
          report.checked.map(file => file.getName) ++ providedJarNames
        for (existing <- IO.listFiles(destination)) {
          if (
            !expectedFileNames.contains(
              existing.getName
            ) && ignoreDependencyIncludeTransitive
              .forall(filter => !existing.getName.contains(filter))
          ) {
            val outdatedArtifact =
              !previousRun
                .exists(analysis =>
                  analysis.libs.exists(a =>
                    a.matchesTargetArtifact(existing) && !a.isOutdated
                  )
                )
            if (outdatedArtifact) {
              logger.info(
                s"Removing outdated std-bits dependency ${existing.getName}."
              )
              IO.delete(existing)
            } else {
              logger.info(
                s"Keeping target ${existing.getName} jar as a dependency. Still up-to-date"
              )
            }
          }
        }
        for (changed <- report.modified -- report.removed) {
          logger.info(
            s"Updating changed std-bits dependency ${changed.getName}."
          )
          updateDependency(changed, destination, logger)
        }
        for (file <- report.unmodified) {
          val dest = destination / file.getName
          if (!dest.exists()) {
            logger.info(s"Adding missing std-bits dependency ${file.getName}.")
            updateDependency(file, destination, logger)
          }
        }
    }
  }

  /** Extract native libraries from `opencv.jar` and put them under
    * `Standard/Image/polyglot/lib` directory. The minimized `opencv.jar` will
    * be put under `Standard/Image/polyglot/java` directory.
    * @param imagePolyglotRoot root dir of Std image polyglot dir
    * @param imageNativeLibs root dir of Std image lib dir
    * @param opencvVersion OpenCV's version
    * @param logger SBT's logger
    * @param updateReport resolution report
    * @param moduleName name of the project where extraction happens
    * @param scalaBinaryVersion Scala's version
    * @param cacheStoreFactory SBT's cache sotre factory
    * @param previousRun summary of previous extraction data, if available
    * @return
    */
  def extractNativeLibsFromOpenCV(
    imagePolyglotRoot: File,
    imageNativeLibs: File,
    opencvVersion: String,
    logger: ManagedLogger,
    updateReport: UpdateReport,
    moduleName: String,
    scalaBinaryVersion: String,
    cacheStoreFactory: CacheStoreFactory,
    previousRun: Option[AnalysisOfExtractedNativeLibs]
  ): AnalysisOfExtractedNativeLibs = {
    if (previousRun.exists(!_.isOutdated)) {
      return previousRun.get
    }
    val extractPrefix = "nu/pattern/opencv"
    val validOsName   = osName()
    val validArch     = arch()

    // Make sure that the native libs in the `lib` directory complies with
    // `org.enso.interpreter.runtime.NativeLibraryFinder`
    def renameFunc(entryName: String): Option[String] = {
      val strippedEntryName = entryName
        .substring(extractPrefix.length + 1)
        .replace("ARMv8", "aarch64")
      if (
        strippedEntryName.contains("linux/ARM") ||
        strippedEntryName.contains("linux/x86_32") ||
        strippedEntryName.contains("README.md")    ||
        // Remove native libs for different platforms
        !strippedEntryName.contains(validOsName) ||
        !strippedEntryName.contains(validArch)
      ) {
        None
      } else {
        Some(
          strippedEntryName
            .replace("linux/x86_64", "amd64")
            .replace("windows/x86_64", "amd64")
            .replace("windows/x86_32", "x86_32")
            .replace("osx/aarch64", "aarch64")
            .replace("osx/x86_64", "amd64")
        )
      }
    }

    val openCvJar = JPMSUtils
      .filterModulesFromUpdate(
        updateReport,
        Seq("org.openpnp" % "opencv" % opencvVersion),
        logger,
        moduleName,
        scalaBinaryVersion,
        shouldContainAll = true
      )
      .head
    val outputJarPath     = (imagePolyglotRoot / "opencv.jar").toPath
    val thinOutputJar     = outputJarPath.toFile
    val extractedFilesDir = imageNativeLibs.toPath
    val extractedLibs = JARUtils.extractFilesFromJar(
      openCvJar.toPath,
      Some(extractPrefix),
      Some(outputJarPath),
      extractedFilesDir,
      renameFunc,
      logger,
      cacheStoreFactory,
      previousRun.flatMap(_.forJar(openCvJar))
    )
    AnalysisOfExtractedNativeLibs(
      openCvJar,
      extractedLibs.getOrElse(Nil),
      Some(thinOutputJar)
    )
  }

  /** Extract native libraries from `tableauhyperapi-<osname>.jar` and put them under
    * `Standard/Tableau/polyglot/lib` directory.
    * @param tableauPolyglotRoot root dir of Std tableau polyglot dir
    * @param tableauNativeLibs root dir of Std tableau lib dir
    * @param tableauVersion Tableau's dependency version
    * @param jnaVersion JNA's version
    * @param logger SBT's logger
    * @param updateReport resolution report
    * @param unmanagedClasspath classpath of unmanaged jars, if any
    * @param moduleName name of the project where extraction happens
    * @param scalaBinaryVersion Scala's version
    * @param cacheStoreFactory SBT's cache sotre factory
    * @param previousRun summary of previous extraction data, if available
    * @return
    */
  def extractNativeLibsFromTableau(
    tableauPolyglotRoot: File,
    tableauNativeLibs: File,
    tableauVersion: String,
    jnaVersion: String,
    jnaJar: File,
    logger: ManagedLogger,
    updateReport: UpdateReport,
    unmanagedClasspath: Classpath,
    moduleName: String,
    scalaBinaryVersion: String,
    cacheStoreFactory: CacheStoreFactory,
    previousRun: Option[AnalysisOfExtractedNativeLibs]
  ): AnalysisOfExtractedNativeLibs = {
    if (previousRun.exists(!_.isOutdated)) {
      return previousRun.get
    }
    val validOsName = osName(unixName = true)
    val validOsExt  = osExt()
    val validArch   = arch().replace("_", "-")
    // Make sure that the native libs in the `lib` directory complies with
    // `org.enso.interpreter.runtime.NativeLibraryFinder`
    def renameFunc(prefix: String)(entryName: String): Option[String] = {
      val strippedEntryName =
        (if (prefix.isEmpty) entryName
         else entryName.substring(prefix.length + 1)).replace("jnilib", "dylib")
      if (
        !strippedEntryName.endsWith(validOsExt) ||
        // Remove native libs for different platforms
        !strippedEntryName.contains(validOsName) ||
        !strippedEntryName.contains(validArch)
      ) {
        None
      } else {
        Some(
          strippedEntryName
            .replace("linux-x86-64", "amd64")
            .replace("win32-x86-64", "amd64")
            .replace("darwin-aarch64", "aarch64")
            .replace("darwin-x86-64", "amd64")
        )
      }
    }

    // Extract native library from tableauhyperapi-$arch's jar
    val tableauSuffixInJar = s"tableauhyperapi-${plainOsName()}"
    val tableauNativeLibJar = unmanagedClasspath
      .map(_.data)
      .filter(f => f.getName.contains(tableauSuffixInJar))
      .head

    val extractedFilesDir = tableauNativeLibs.toPath
    val extractedTableauLibs = JARUtils.extractFilesFromJar(
      tableauNativeLibJar.toPath,
      None,
      None,
      extractedFilesDir,
      renameFunc(""),
      logger,
      cacheStoreFactory,
      previousRun.flatMap(_.forJar(tableauNativeLibJar))
    )
    val extractedTableau = ExtractedNativeLibSummary(
      tableauNativeLibJar,
      extractedTableauLibs.getOrElse(Nil),
      None
    )

    // Extract native library from jna's jar
    val outputJnaJarPath =
      (tableauPolyglotRoot / s"jna-${validOsName}-$jnaVersion.jar").toPath
    val outputJnaJar  = outputJnaJarPath.toFile
    val extractPrefix = "com/sun/jna"
    val extractedJnaLibs = JARUtils.extractFilesFromJar(
      jnaJar.toPath,
      Some(extractPrefix),
      Some(outputJnaJarPath),
      extractedFilesDir,
      renameFunc(extractPrefix),
      logger,
      cacheStoreFactory,
      previousRun.flatMap(_.forJar(jnaJar))
    )
    val extractedJna = ExtractedNativeLibSummary(
      jnaJar,
      extractedJnaLibs.getOrElse(Nil),
      Some(outputJnaJar)
    )
    AnalysisOfExtractedNativeLibs(extractedTableau :: extractedJna :: Nil)
  }

  /** Extract native libraries from `grpc-netty-shaded-<version>.jar` and put them under
    * `Standard/Google_Api/polyglot/lib` directory.
    * @param grpcPolyglotRoot root dir of Std Google polyglot dir
    * @param grpcNativeLibs root dir of Std Google lib dir
    * @param grpcVersion GRPC's library version
    * @param updateReport resolution report
    * @param logger SBT's logger
    * @param moduleName name of the project where extraction happens
    * @param scalaBinaryVersion Scala's version
    * @param cacheStoreFactory SBT's cache sotre factory
    * @param previousRun summary of previous extraction data, if available
    * @return
    */
  def extractNativeLibsFromGrpc(
    grpcPolyglotRoot: File,
    grpcNativeLibs: File,
    grpcVersion: String,
    updateReport: UpdateReport,
    logger: ManagedLogger,
    moduleName: String,
    scalaBinaryVersion: String,
    cacheStoreFactory: CacheStoreFactory,
    previousRun: Option[AnalysisOfExtractedNativeLibs]
  ): AnalysisOfExtractedNativeLibs = {
    if (previousRun.exists(!_.isOutdated)) {
      return previousRun.get
    }
    val validOsName = osName()
    val validOsExt  = osExt()
    val validArch   = arch().replace("-", "_")
    // Make sure that the native libs in the `lib` directory complies with
    // `org.enso.interpreter.runtime.NativeLibraryFinder`
    def renameFunc(prefix: String)(entryName: String): Option[String] = {
      val strippedEntryName =
        (if (prefix.isEmpty) entryName
         else entryName.substring(prefix.length + 1)).replace("jnilib", "dylib")
      if (
        !strippedEntryName.endsWith(validOsExt) ||
        // Remove native libs for different platforms
        !(strippedEntryName.contains(validOsName) || strippedEntryName.contains(
          "native_epoll" // native-epol does not have os info in the name
        )) ||
        !strippedEntryName.contains(validArch)
      ) {
        None
      } else {
        Some(strippedEntryName)
      }
    }

    val grpcJar = JPMSUtils
      .filterModulesFromUpdate(
        updateReport,
        Seq("io.grpc" % "grpc-netty-shaded" % grpcVersion),
        logger,
        moduleName,
        scalaBinaryVersion,
        shouldContainAll = true
      )
      .head
    val outputGrpcNettyShaded =
      (grpcPolyglotRoot / s"grpc-netty-shaded-thin-$grpcVersion.jar").toPath
    val extractPrefix = "META-INF/native"
    val extractedLibs = JARUtils.extractFilesFromJar(
      grpcJar.toPath,
      Some(extractPrefix),
      Some(outputGrpcNettyShaded),
      grpcNativeLibs.toPath,
      renameFunc(extractPrefix),
      logger,
      cacheStoreFactory,
      previousRun.flatMap(_.forJar(grpcJar))
    )
    AnalysisOfExtractedNativeLibs(
      grpcJar,
      extractedLibs.getOrElse(Nil),
      Some(outputGrpcNettyShaded.toFile)
    )
  }

  def ensureDirExistsAndIsClean(
    path: Path,
    logger: sbt.util.Logger,
    forceClean: Boolean = true
  ): Unit = {
    require(path != null)
    val dir = path.toFile
    if (dir.exists && dir.isDirectory) {
      // Clean previous contents
      if (forceClean)
        IO.delete(IO.listFiles(dir))
    } else {
      try {
        IO.createDirectory(dir)
      } catch {
        case e: IOException =>
          logger.err(
            s"Failed to create directory $path: ${e.getMessage}"
          )
          e.printStackTrace(System.err)
      }
    }
  }

  /** Inspired by `org.enso.pkg.NativeLibraryFinder`
    */
  private def osName(unixName: Boolean = false): String = {
    var osName = System.getProperty("os.name").toLowerCase(Locale.ENGLISH)
    if (osName.contains(" ")) {
      // Strip version
      osName = osName.substring(0, osName.indexOf(' '))
    }
    if (osName.contains("linux")) {
      "linux"
    } else if (osName.contains("mac")) {
      if (unixName) "darwin" else "osx"
    } else if (osName.contains("windows")) {
      if (unixName) "win32" else "windows"
    } else {
      throw new IllegalStateException(s"Unsupported OS: $osName")
    }
  }

  // A list of support OS names
  def allSupportedOs(): List[String] = List("linux", "osx", "windows")

  // ${os-name}-${arch} plaftorm name
  def currentPlatformSuffix(): String = {
    osName() + "-" + arch()
  }

  // Human-accepted name of OS. One of many at least.
  def plainOsName(): String = {
    var osName = System.getProperty("os.name").toLowerCase(Locale.ENGLISH)
    if (osName.contains(" ")) {
      // Strip version
      osName = osName.substring(0, osName.indexOf(' '))
    }
    if (osName.contains("linux")) {
      "linux"
    } else if (osName.contains("mac")) {
      "macos"
    } else if (osName.contains("windows")) {
      "windows"
    } else {
      throw new IllegalStateException(s"Unsupported OS: $osName")
    }
  }

  private def osExt(): String = {
    var osName = System.getProperty("os.name").toLowerCase(Locale.ENGLISH)
    if (osName.contains(" ")) {
      // Strip version
      osName = osName.substring(0, osName.indexOf(' '))
    }
    if (osName.contains("linux")) {
      ".so"
    } else if (osName.contains("mac")) {
      ".dylib"
    } else if (osName.contains("windows")) {
      ".dll"
    } else {
      throw new IllegalStateException(s"Unsupported OS: $osName")
    }
  }

  /** Inspired by `org.enso.pkg.NativeLibraryFinder`
    */
  private def arch(): String = {
    val arch = System.getProperty("os.arch").toLowerCase(Locale.ENGLISH)
    arch
      .replace("amd64", "x86_64")
  }

  private def updateDependency(
    jar: File,
    destinationDir: File,
    logger: ManagedLogger
  ): Unit = {
    val destination = destinationDir / jar.getName
    IO.copyFile(jar, destination)
  }

  /** Builds a single standard library package `name`. Should only be used
    * in tasks used in local development.
    *
    * @param name name of the package, see `stdBitsProjects` in build.sbt
    * @param root top directory where distribution is being built
    * @param cache used for persisting the cached information
    * @param log logger used in the task
    * @param defaultDevEnsoVersion default `dev` version
    */
  def buildStdLibPackage(
    name: String,
    root: File,
    cacheFactory: sbt.util.CacheStoreFactory,
    log: sbt.Logger,
    defaultDevEnsoVersion: String
  ) = {
    log.info(s"Building standard library package for '$name'")
    val prefix        = "Standard"
    val targetPkgRoot = root / "lib" / prefix / name / defaultDevEnsoVersion
    val sourceDir = file(
      s"distribution/lib/$prefix/$name/$defaultDevEnsoVersion"
    )
    if (!sourceDir.exists) {
      throw new RuntimeException("Invalid standard library package " + name)
    }
    val result = DistributionPackage.copyDirectoryIncremental(
      source      = file(s"distribution/lib/$prefix/$name/$defaultDevEnsoVersion"),
      destination = targetPkgRoot,
      cache       = cacheFactory.sub("engine-libraries").make(s"$prefix.$name")
    )
    if (result) {
      log.info(s"Package '$name' has been updated")
    } else {
      log.info(s"No changes detected for '$name' package")
    }
  }

}
