//! Traits providing abstraction over transport used by the JSON-RPC client.

use crate::prelude::*;

use failure::Error;
use futures::channel::mpsc::unbounded;
use futures::channel::mpsc::UnboundedReceiver;
use futures::channel::mpsc::UnboundedSender;

/// A transport that facilitate JSON-RPC protocol.
///
/// Must allow sending and receiving text messages. Additionally, connection at
/// any point might be lost for any reason.
///
/// Typical implementation would use WebSockets but it can be also a mock for
/// tests.
pub trait Transport: Debug {
    /// Send a text message.
    fn send_text(&mut self, message: &str) -> Result<(), Error>;

    /// Send a binary data message.
    fn send_binary(&mut self, message: &[u8]) -> Result<(), Error>;

    /// Set up a channel which shall be used to receive events from the `Transport`.
    fn set_event_transmitter(&mut self, transmitter: UnboundedSender<TransportEvent>);

    /// Sets up a stream's receiver yielding `TransportEvent`s.
    fn establish_event_stream(&mut self) -> UnboundedReceiver<TransportEvent> {
        let (event_transmitter, event_receiver) = unbounded();
        self.set_event_transmitter(event_transmitter);
        event_receiver
    }
}

/// An event generated by the `Transport`.
#[derive(Debug)]
pub enum TransportEvent {
    /// A text message with has been received.
    TextMessage(String),
    /// A text message with has been received.
    BinaryMessage(Vec<u8>),
    /// A socket has been opened.
    Opened,
    /// A socket has been closed by the peer.
    /// This event may be also emitted when reconnecting has failed.
    Closed,
}
