[build]
target-dir = "target/rust/"
rustflags = ["--cfg", "tokio_unstable"]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld"
# Static linking is required to avoid the need for the Visual C++ Redistributable. We care about this primarily for our
# installer binary package.
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-Clink-arg=-fuse-ld=lld"]
