extra-deps: [ghc-session-0.1.2.0, error-util-0.0.1.1, cond-0.4.1.1, ghc-mtl-1.2.1.0,
  serialport-0.4.7, aeson-1.0.2.1]
ghc-options: {'*': -DFastCompilation -fenable-rewrite-rules -threaded -funbox-strict-fields
    -O0 -fconstraint-solver-iterations=100}
local-bin-path: ./bin
packages:
- {location: .}
- {extra-dep: true, location: ../core}
- extra-dep: true
  location: {commit: 9d451ec9eeb06d4e28bbd66915fe1698bae2f001, git: 'https://github.com/luna/container.git'}
- extra-dep: true
  location: {commit: 6b9f0f6ec43e83c88f28e0fe051ac74516c35605, git: 'https://github.com/luna/data-pool.git'}
- extra-dep: true
  location: {commit: 862e09721498fe6f4d98cd7457e7ce942a56386a, git: 'https://github.com/luna/convert.git'}
- extra-dep: true
  location: {commit: 23a039debfd51a9b7f46b5e106feb30839960e37, git: 'https://github.com/luna/data-base.git'}
- extra-dep: true
  location: {commit: 211164cbb214790b26fb5bac7f2771d18c1b9574, git: 'https://github.com/luna/data-construction.git'}
- extra-dep: true
  location: {commit: 8cd6c328b9d06344ed529bb3bcebbf27e8afbc23, git: 'https://github.com/luna/data-layer.git'}
- extra-dep: true
  location: {commit: c20f35c8e2f25fd84df385e8646b125d9fca8ac4, git: 'https://github.com/luna/data-repr.git'}
- extra-dep: true
  location: {commit: 604145037427b944050f1959bcdffc375328f72c, git: 'https://github.com/luna/data-result.git'}
- extra-dep: true
  location: {commit: 62dca5524c1fadb19339b8257809d6c872b5f82d, git: 'https://github.com/luna/dependent-state.git'}
- extra-dep: true
  location: {commit: 41fb55a6ff9cee8166df86ee71430a7e9b20ed65, git: 'https://github.com/luna/functor-utils.git'}
- extra-dep: true
  location: {commit: 5dc5b731a4313e44d55677ed6b9f38456feb2d56, git: 'https://github.com/luna/impossible.git'}
- extra-dep: true
  location: {commit: 446533d1169324542c220a7fe179616759fcbd8a, git: 'https://github.com/luna/lens-utils.git'}
- extra-dep: true
  location: {commit: 53538017ad47a0a473233577595d8ac6e3eae9a0, git: 'https://github.com/luna/poly-control.git'}
- extra-dep: true
  location: {commit: 5f117ec437aa371743f2afa1e32611305ddb4583, git: 'https://github.com/luna/prologue.git'}
- extra-dep: true
  location: {commit: 7c9eab45f65ab98290282e11d19e39401830ab9c, git: 'https://github.com/luna/type-cache.git'}
- extra-dep: true
  location: {commit: 792a086e5f9a1eab6e9a2e14d3515b024a0641b6, git: 'https://github.com/luna/typelevel.git'}
- extra-dep: true
  location: {commit: 211164cbb214790b26fb5bac7f2771d18c1b9574, git: 'https://github.com/luna/data-construction.git'}
- extra-dep: true
  location: {commit: adb894846d34ceaa005961bd8fe676023cf1b036, git: 'https://github.com/luna/data-prop.git'}
- extra-dep: true
  location: {commit: 85558940cfa03020eb7b47d98577a86253b99742, git: 'https://github.com/luna/data-rtuple.git'}
- extra-dep: true
  location: {commit: f7124ecbfa4ce8802e3c1431e54300188616fe64, git: 'https://github.com/luna/data-shell.git'}
- extra-dep: true
  location: {commit: af5a618f5813ac639a6760836a6d6fa7ef5af1da, git: 'https://github.com/luna/visualization-api.git'}
resolver: lts-7.9
