name: haskell-benchmark
version: 0.1.0.0
github: "https://github.com/enso-org/enso"
author: "Ara Adkins"
maintainer: "ara.adkins@enso.org"
copyright: "Enso Team 2020"

description: A benchmark for comparing Haskell to Enso.

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - base
    - deepseq

benchmarks:
  haskell-benchmark:
    main: Main.hs
    source-dirs:
      - test/bench
    dependencies:
      - base
      - criterion
      - deepseq
      - haskell-benchmark

default-extensions:
  - AllowAmbiguousTypes
  - ApplicativeDo
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DuplicateRecordFields
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - LiberalTypeSynonyms
  - MonadComprehensions
  - MultiWayIf
  - NamedWildCards
  - NegativeLiterals
  - NoImplicitPrelude
  - NumDecimals
  - OverloadedLabels
  - OverloadedStrings
  - PatternSynonyms
  - QuasiQuotes
  - RankNTypes
  - RecursiveDo
  - ScopedTypeVariables
  - StandaloneDeriving
  - Strict
  - StrictData
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators
  - UnicodeSyntax
  - ViewPatterns
