[package]
name = "enso-build-ci-gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
ide-ci = { path = "../ci_utils" }
enso-build = { path = "../build" }
serde_yaml = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
