//! This module reexports several commonly used types defined in the standard library.

pub use std::any::Any;
pub use std::borrow::Cow;
pub use std::cell::Cell;
pub use std::cell::Ref;
pub use std::cell::RefCell;
pub use std::cell::RefMut;
pub use std::collections::BTreeMap;
pub use std::collections::HashMap;
pub use std::collections::HashSet;
pub use std::convert::identity;
pub use std::convert::TryFrom;
pub use std::convert::TryInto;
pub use std::fmt::Display;
pub use std::fmt;
pub use std::hash::Hash;
pub use std::iter::FromIterator;
pub use std::iter;
pub use std::marker::PhantomData;
pub use std::ops::Add;
pub use std::ops::Deref;
pub use std::ops::DerefMut;
pub use std::ops::Index;
pub use std::ops::IndexMut;
pub use std::rc::Rc;
pub use std::rc::Weak;
pub use std::slice::SliceIndex;
pub use std::slice;
