logging-service {
  logger {
    org.enso.example = info
  }
  appenders = [
    {
      name = "memory"
    },
    {
      name = "console"
      pattern = "[%level] [%d{yyyy-MM-ddTHH:mm:ssXXX}] [%logger] %msg%n"
    }
  ]
  default-appender = console
  log-level = "info"
}
