package org.enso.languageserver.util.file

import org.enso.languageserver.filemanager.Path
import org.enso.languageserver.protocol.binary.{Path => BinaryPath}

object PathUtils {

  /**
    * Converts a path generated by the FlatBuffers lib. to value of type [[Path]].
    *
    * @param path a binary path
    * @return
    */
  def convertBinaryPath(path: BinaryPath): Path = {
    val rootId = UuidUtils.convertEnsoUuid(path.rootId())
    val segments =
      (0 until path.segmentsLength()).foldRight(List.empty[String]) {
        case (index, tail) => path.segmentsVector().get(index) :: tail
      }

    Path(rootId, segments.toVector)
  }

}
