[package]
name = "ide-ci"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = { workspace = true }
async-compression = { version = "0.3.12", features = ["tokio", "gzip"] }
async-trait = "0.1.78"
bincode = "1.3.3"
bytes = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
convert_case = { workspace = true }
data-encoding = "2.3.2"
dependency_runner = "1.1.0"
derive-where = { workspace = true }
derive_more = { workspace = true }
dirs = { workspace = true }
enso-build-base = { path = "../base" }
enso-zst = { path = "../../lib/rust/zst" }
flate2 = { workspace = true }
flume = "0.10.10"
fs_extra = "1.3.0"
futures = { workspace = true }
futures-util = { workspace = true }
glob = "0.3.0"
headers = "0.3.7"
http-serde = "1.1.0"
indicatif = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
mime = { workspace = true }
multimap = { workspace = true }
new_mime_guess = { workspace = true }
octocrab = { workspace = true }
path-absolutize = { workspace = true }
pathdiff = "0.2.1"
path-slash = "0.2.1"
portpicker = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
sha2 = { workspace = true }
strum = { workspace = true }
symlink = "0.1.0"
sysinfo = { workspace = true }
tar = { workspace = true }
tempfile = "3.2.0"
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
unicase = "2.6.0"
url = "2.2.2"
uuid = { version = "1.1.0", features = ["v4", "serde"] }
walkdir = { workspace = true }
which = "5.0.0"
zip = { version = "0.6.2", default-features = false, features = ["deflate"] }
base64 = "0.21.0"

[dev-dependencies]
wiremock = "0.5.10"

[lints]
workspace = true
