name: ✨ GUI

on:
  pull_request:
    types:
      - labeled

concurrency:
  group: "gui-chromatic-tests-label-trigger"
  cancel-in-progress: true

run-name: "GUI Chromatic Tests Label Trigger"

permissions:
  issues: write
  pull-requests: write
  contents: write
  statuses: write

jobs:
  trigger-chromatic-tests:
    name: 🕹️ Trigger Chromatic Tests
    if: "contains(github.event.pull_request.labels.*.name, 'CI: Run Chromatic')"
    uses: ./.github/workflows/storybook.yml
    with:
      skip-label: "CI: Run Chromatic"
    secrets: inherit
