import { GraphDb, type NodeId } from '$/providers/openedProjects/graph/graphDatabase'
import {
  ComputedValueRegistry,
  TypeInfo,
} from '$/providers/openedProjects/project/computedValueRegistry'
import { SuggestionDb } from '$/providers/openedProjects/suggestionDatabase'
import { makeMethod, makeType } from '$/providers/openedProjects/suggestionDatabase/mockSuggestion'
import { useComponentBrowserInput } from '@/components/ComponentBrowser/input'
import { Ast } from '@/util/ast'
import { MutableModule } from '@/util/ast/abstract'
import { Vec2 } from '@/util/data/vec2'
import { stdPath } from '@/util/projectPath'
import { tryIdentifier } from '@/util/qualifiedName'
import { unwrap } from 'enso-common/src/utilities/data/result'
import { describe, expect, test } from 'vitest'
import { assert } from 'ydoc-shared/util/assert'
import { Range } from 'ydoc-shared/util/data/range'

const operator1Id = '3d0e9b96-3ca0-4c35-a820-7d3a1649de55' as NodeId
const operator2Id = '5eb16101-dd2b-4034-a6e2-476e8bfa1f2b' as NodeId

function mockGraphDb() {
  const computedValueRegistryMock = ComputedValueRegistry.Mock()
  computedValueRegistryMock.db.set(operator1Id, {
    typeInfo: TypeInfo.fromParsedTypes([stdPath('Standard.Base.Number')], [])!,
    methodCall: undefined,
    payload: { type: 'Value' },
    profilingInfo: [],
    evaluationId: 1,
  })
  const db = GraphDb.Mock(computedValueRegistryMock)
  db.mockNode('operator1', operator1Id, 'Data.read')
  db.mockNode('operator2', operator2Id)
  return db
}

test.each`
  inputContent   | expectedLiteral
  ${'read'}      | ${undefined}
  ${'operator1'} | ${undefined}
  ${'12 + 14'}   | ${undefined}
  ${'12'}        | ${'12'}
  ${'12.6'}      | ${'12.6'}
  ${'-12'}       | ${'-12'}
  ${'-12.6'}     | ${'-12.6'}
  ${'- 12.6'}    | ${undefined /* in Enso this is partial OprApp, not negation */}
  ${'"text"'}    | ${'"text"'}
  ${"'text'"}    | ${"'text'"}
  ${"'text"}     | ${"'text'"}
  ${"'''text"}   | ${"'''text"}
`('Reading literal from $inputContent', ({ inputContent, expectedLiteral }) => {
  const input = useComponentBrowserInput(() => false, mockGraphDb(), new SuggestionDb())
  input.reset({ type: 'newNode' })
  input.content = { text: inputContent, selection: Range.empty }
  assert(input.interpretation.mode === 'componentBrowsing')
  expect(input.interpretation.literal?.code()).toBe(expectedLiteral)
})

test.each`
  inputContent     | source         | expectedCode
  ${'read'}        | ${'operator1'} | ${'operator1.read'}
  ${'read'}        | ${'operator2'} | ${'operator2.read'}
  ${'read "file"'} | ${'operator2'} | ${'operator2.read "file"'}
  ${'+ 2'}         | ${'operator1'} | ${'operator1 + 2'}
  ${'+ 3'}         | ${'operator2'} | ${'operator2 + 3'}
  ${'+2'}          | ${'operator1'} | ${'operator1+2'}
  ${'-2'}          | ${'operator1'} | ${'operator1-2'}
`(
  'Code generated by CB from $inputContent with source node $sourceNode',
  ({ inputContent, source, expectedCode }) => {
    const db = mockGraphDb()
    const input = useComponentBrowserInput(() => false, db, new SuggestionDb())
    const sourcePort = db.getNodeFirstOutputPort(db.getIdentDefiningNode(source))
    assert(sourcePort != null)
    input.reset({ type: 'newNode', sourcePort })
    input.content = { text: inputContent, selection: Range.empty }
    expect(input.code).toBe(expectedCode)
  },
)

function mockSuggestionDb() {
  const suggestionDb = new SuggestionDb()
  suggestionDb.set(1, makeType('Standard.Base.Number'))
  suggestionDb.set(2, makeMethod('Standard.Base.Any.Any.to_text'))
  suggestionDb.set(3, makeMethod('Standard.Base.Number.add'))
  suggestionDb.set(4, makeMethod('Standard.Base.Type.after_cast'))
  return suggestionDb
}

test.each`
  suggestionId | expectedCode
  ${2}         | ${'operator1.to_text '}
  ${3}         | ${'operator1.add '}
  ${4}         | ${'operator1:Type . after_cast '}
`('Applying suggestion with possible type casting', ({ suggestionId, expectedCode }) => {
  const db = mockGraphDb()
  const suggestionDb = mockSuggestionDb()
  const input = useComponentBrowserInput(() => false, db, suggestionDb)
  const sourcePort = db.getNodeFirstOutputPort(db.getIdentDefiningNode('operator1'))
  assert(sourcePort != null)
  input.reset({ type: 'newNode', sourcePort })
  input.applySuggestion(suggestionId, undefined)
  expect(input.code).toBe(expectedCode)
})

const aiNodeId = '7c1d8e34-9f0a-4b6e-bd11-1a4c0f2e8b73' as NodeId
const codeNodeId = '8b2e7c45-7e90-4d2f-c1a4-2c5f3d8e9d72' as NodeId

function mockGraphDbWithAiNode() {
  const computedValueRegistryMock = ComputedValueRegistry.Mock()
  const db = GraphDb.Mock(computedValueRegistryMock)
  db.mockNode('operator1', operator1Id, 'Data.read')
  // Build an AI-marked assignment by hand (mockNode doesn't accept a documentation string).
  const edit = MutableModule.Transient()
  const aiBinding = unwrap(tryIdentifier('ai_node1'))
  const aiExpr = Ast.parseExpression('Main.ai_generated 0', edit)!
  const aiAssignment = Ast.Assignment.new(aiBinding, aiExpr, {
    edit,
    documentation: 'AI: count things',
  })
  db.nodeIdToNode.set(aiNodeId, {
    type: 'component',
    position: Vec2.Zero,
    height: undefined,
    vis: undefined,
    prefixes: { enableRecording: undefined },
    primaryApplication: { function: null, accessChain: null, selfArgument: null },
    colorOverride: undefined,
    conditionalPorts: new Set(),
    outerAst: aiAssignment,
    pattern: aiAssignment.pattern,
    rootExpr: aiExpr,
    innerExpr: aiExpr,
    zIndex: 1,
    argIndex: undefined,
    isExpanded: false,
  })
  // A vanilla code node — same shape mockNode would produce, used for editNode-non-AI tests.
  db.mockNode('code_node1', codeNodeId, 'operator1.add 1')
  return db
}

describe('useComponentBrowserInput mode selection', () => {
  test('newNode defaults to componentBrowsing when AI is unavailable', () => {
    const input = useComponentBrowserInput(() => false, mockGraphDb(), new SuggestionDb())
    input.reset({ type: 'newNode' })
    expect(input.selectedMode).toBe('componentBrowsing')
    expect(input.modeLocked).toBe(false)
    expect(input.interpretation.mode).toBe('componentBrowsing')
  })

  test('newNode defaults to aiPrompt when AI is available', () => {
    const input = useComponentBrowserInput(() => true, mockGraphDb(), new SuggestionDb())
    input.reset({ type: 'newNode' })
    expect(input.selectedMode).toBe('aiPrompt')
    expect(input.modeLocked).toBe(false)
    expect(input.interpretation.mode).toBe('aiPrompt')
  })

  test('setSelectedMode switches between unlocked modes', () => {
    const input = useComponentBrowserInput(() => true, mockGraphDb(), new SuggestionDb())
    input.reset({ type: 'newNode' })
    expect(input.selectedMode).toBe('aiPrompt')
    input.setSelectedMode('componentBrowsing')
    expect(input.selectedMode).toBe('componentBrowsing')
    expect(input.interpretation.mode).toBe('componentBrowsing')
    input.setSelectedMode('codeEditing')
    expect(input.selectedMode).toBe('codeEditing')
    expect(input.interpretation.mode).toBe('codeEditing')
  })

  test('editNode on an AI assignment locks into aiPrompt with the previous prompt', () => {
    const input = useComponentBrowserInput(() => true, mockGraphDbWithAiNode(), new SuggestionDb())
    input.reset({ type: 'editNode', node: aiNodeId, cursorPos: 0 })
    expect(input.selectedMode).toBe('aiPrompt')
    expect(input.modeLocked).toBe(true)
    expect(input.text).toBe('count things')
    assert(input.interpretation.mode === 'aiPrompt')
    expect(input.interpretation.prompt).toBe('count things')
  })

  test('editNode on an AI assignment falls back to codeEditing when AI is unavailable', () => {
    const input = useComponentBrowserInput(() => false, mockGraphDbWithAiNode(), new SuggestionDb())
    input.reset({ type: 'editNode', node: aiNodeId, cursorPos: 0 })
    expect(input.selectedMode).toBe('codeEditing')
    expect(input.modeLocked).toBe(true)
    assert(input.interpretation.mode === 'codeEditing')
    // The original AI call expression is shown for inline editing.
    expect(input.text).toBe('Main.ai_generated 0')
  })

  test('editNode on a non-AI assignment locks into codeEditing', () => {
    const input = useComponentBrowserInput(() => true, mockGraphDbWithAiNode(), new SuggestionDb())
    input.reset({ type: 'editNode', node: codeNodeId, cursorPos: 0 })
    expect(input.selectedMode).toBe('codeEditing')
    expect(input.modeLocked).toBe(true)
    assert(input.interpretation.mode === 'codeEditing')
  })

  test('setSelectedMode is a no-op when modeLocked', () => {
    const input = useComponentBrowserInput(() => true, mockGraphDbWithAiNode(), new SuggestionDb())
    input.reset({ type: 'editNode', node: codeNodeId, cursorPos: 0 })
    expect(input.selectedMode).toBe('codeEditing')
    input.setSelectedMode('aiPrompt')
    expect(input.selectedMode).toBe('codeEditing')
    input.setSelectedMode('componentBrowsing')
    expect(input.selectedMode).toBe('codeEditing')
  })

  test('applySuggestion switches to codeEditing and exposes the applied entry', () => {
    const input = useComponentBrowserInput(() => true, mockGraphDb(), mockSuggestionDb())
    input.reset({ type: 'newNode' })
    expect(input.selectedMode).toBe('aiPrompt')
    input.applySuggestion(3, undefined)
    expect(input.selectedMode).toBe('codeEditing')
    assert(input.interpretation.mode === 'codeEditing')
    expect(input.interpretation.appliedSuggestion).toBeDefined()
  })

  test('setSelectedMode away from codeEditing clears the applied-suggestion association', () => {
    const input = useComponentBrowserInput(() => true, mockGraphDb(), mockSuggestionDb())
    input.reset({ type: 'newNode' })
    input.applySuggestion(3, undefined)
    assert(input.interpretation.mode === 'codeEditing')
    expect(input.interpretation.appliedSuggestion).toBeDefined()
    input.setSelectedMode('aiPrompt')
    input.setSelectedMode('codeEditing')
    assert(input.interpretation.mode === 'codeEditing')
    expect(input.interpretation.appliedSuggestion).toBeUndefined()
  })

  test('switchToCodeEditMode sets codeEditing with no applied suggestion', () => {
    const input = useComponentBrowserInput(() => true, mockGraphDb(), mockSuggestionDb())
    input.reset({ type: 'newNode' })
    input.applySuggestion(3, undefined)
    input.switchToCodeEditMode()
    assert(input.interpretation.mode === 'codeEditing')
    expect(input.interpretation.appliedSuggestion).toBeUndefined()
  })
})
